name: vahomemath_gis
version: 1.0.0
config-version: 2
profile: vahomemath_gis
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages", "logs"]

models:
  vahomemath_gis:
    staging:
      +materialized: view
      +schema: gis_staging
    intermediate:
      +materialized: view
      +schema: gis_intermediate
    marts:
      +materialized: table
      +schema: gis_analytics

seeds:
  vahomemath_gis:
    +schema: gis_analytics
