"""add scheduling orchestration operations

Revision ID: 20260830_0012
Revises: 20260830_0011
Create Date: 2026-08-30 14:15:16.359796
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260830_0012'
down_revision: Union[str, None] = '20260830_0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('handler_key', sa.String(length=100), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=True),
    sa.Column('paid_provider', sa.Boolean(), nullable=False),
    sa.Column('default_estimated_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['gis_core.data_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_pipeline_definition_key'),
    schema='gis_core'
    )
    op.create_table('pipeline_dependency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('upstream_pipeline_id', sa.UUID(), nullable=False),
    sa.Column('downstream_pipeline_id', sa.UUID(), nullable=False),
    sa.Column('policy', sa.Enum('ALL_SUCCESS', 'ANY_SUCCESS', 'ALWAYS', name='dependency_policy', schema='gis_core'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('upstream_pipeline_id <> downstream_pipeline_id', name='ck_pipeline_dependency_self'),
    sa.ForeignKeyConstraint(['downstream_pipeline_id'], ['gis_core.pipeline_definition.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['gis_core.tenant.id'], ),
    sa.ForeignKeyConstraint(['upstream_pipeline_id'], ['gis_core.pipeline_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis_core'
    )
    op.create_index('ix_pipeline_dependency_downstream', 'pipeline_dependency', ['tenant_id', 'site_id', 'downstream_pipeline_id'], unique=False, schema='gis_core')
    op.create_index('uq_pipeline_dependency_scope', 'pipeline_dependency', ['tenant_id', 'site_id', 'upstream_pipeline_id', 'downstream_pipeline_id'], unique=True, schema='gis_core', postgresql_nulls_not_distinct=True)
    op.create_table('schedule_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('data_source_connection_id', sa.UUID(), nullable=True),
    sa.Column('rights_policy_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('ENABLED', 'DISABLED', name='schedule_status', schema='gis_core'), nullable=False),
    sa.Column('next_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=False),
    sa.Column('exponential_backoff', sa.Boolean(), nullable=False),
    sa.Column('freshness_sla_seconds', sa.Integer(), nullable=True),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('freshness_sla_seconds IS NULL OR freshness_sla_seconds > 0', name='ck_schedule_freshness_sla'),
    sa.CheckConstraint('max_attempts >= 1', name='ck_schedule_max_attempts'),
    sa.CheckConstraint('retry_delay_seconds >= 0', name='ck_schedule_retry_delay'),
    sa.ForeignKeyConstraint(['data_source_connection_id'], ['gis_core.data_source_connection.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['gis_core.organization.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['gis_core.pipeline_definition.id'], ),
    sa.ForeignKeyConstraint(['rights_policy_id'], ['gis_core.data_rights_policy.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'site_id'], ['gis_core.site.tenant_id', 'gis_core.site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_schedule_definition_tenant_name'),
    schema='gis_core'
    )
    op.create_index('ix_schedule_due', 'schedule_definition', ['status', 'next_scheduled_at'], unique=False, schema='gis_core')
    op.create_index('ix_schedule_tenant_site', 'schedule_definition', ['tenant_id', 'site_id'], unique=False, schema='gis_core')
    op.create_table('cost_budget',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('data_source_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_id', sa.UUID(), nullable=True),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('daily_limit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('monthly_limit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('per_run_limit', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('daily_limit IS NULL OR daily_limit >= 0', name='ck_budget_daily'),
    sa.CheckConstraint('monthly_limit IS NULL OR monthly_limit >= 0', name='ck_budget_monthly'),
    sa.CheckConstraint('per_run_limit IS NULL OR per_run_limit >= 0', name='ck_budget_per_run'),
    sa.ForeignKeyConstraint(['data_source_id'], ['gis_core.data_source.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['gis_core.pipeline_definition.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['gis_core.schedule_definition.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['gis_core.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis_core'
    )
    op.create_index('ix_cost_budget_tenant', 'cost_budget', ['tenant_id', 'active'], unique=False, schema='gis_core')
    op.create_index('uq_cost_budget_scope', 'cost_budget', ['tenant_id', 'site_id', 'data_source_id', 'pipeline_id', 'schedule_id'], unique=True, schema='gis_core', postgresql_nulls_not_distinct=True)
    op.create_table('freshness_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_next_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('freshness_sla_seconds', sa.Integer(), nullable=True),
    sa.Column('stale_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['gis_core.pipeline_definition.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['gis_core.schedule_definition.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['gis_core.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis_core'
    )
    op.create_index('ix_freshness_stale', 'freshness_state', ['tenant_id', 'stale_since'], unique=False, schema='gis_core')
    op.create_index('uq_freshness_scope', 'freshness_state', ['tenant_id', 'site_id', 'pipeline_id', 'schedule_id'], unique=True, schema='gis_core', postgresql_nulls_not_distinct=True)
    op.create_table('scheduled_target',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_key', sa.Text(), nullable=False),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['gis_core.schedule_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['gis_core.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'target_type', 'target_key', name='uq_scheduled_target'),
    schema='gis_core'
    )
    op.create_index('ix_scheduled_target_tenant', 'scheduled_target', ['tenant_id', 'site_id'], unique=False, schema='gis_core')
    op.create_table('orchestration_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('data_source_connection_id', sa.UUID(), nullable=True),
    sa.Column('rights_policy_id', sa.UUID(), nullable=True),
    sa.Column('upstream_run_id', sa.UUID(), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('trigger_type', sa.Enum('SCHEDULED', 'MANUAL', 'RETRY', 'BACKFILL', 'DEPENDENCY', name='trigger_type', schema='gis_core'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WAITING_DEPENDENCY', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'BLOCKED', 'CANCELLED', name='orchestration_status', schema='gis_core'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backfill_start', sa.Date(), nullable=True),
    sa.Column('backfill_end', sa.Date(), nullable=True),
    sa.Column('estimated_provider_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('actual_provider_cost', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('error_classification', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('actual_provider_cost IS NULL OR actual_provider_cost >= 0', name='ck_orchestration_actual_cost'),
    sa.CheckConstraint('backfill_end IS NULL OR backfill_end >= backfill_start', name='ck_orchestration_backfill_bounds'),
    sa.CheckConstraint('backfill_end IS NULL OR backfill_start IS NOT NULL', name='ck_orchestration_backfill_pair'),
    sa.CheckConstraint('estimated_provider_cost >= 0', name='ck_orchestration_estimated_cost'),
    sa.ForeignKeyConstraint(['data_source_connection_id'], ['gis_core.data_source_connection.id'], ),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['gis_core.ingestion_run.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['gis_core.organization.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['gis_core.pipeline_definition.id'], ),
    sa.ForeignKeyConstraint(['rights_policy_id'], ['gis_core.data_rights_policy.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['gis_core.schedule_definition.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['gis_core.scheduled_target.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'site_id'], ['gis_core.site.tenant_id', 'gis_core.site.id'], ),
    sa.ForeignKeyConstraint(['upstream_run_id'], ['gis_core.orchestration_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis_core'
    )
    op.create_index('ix_orchestration_history', 'orchestration_run', ['tenant_id', 'site_id', 'pipeline_id', 'requested_at'], unique=False, schema='gis_core')
    op.create_index('ix_orchestration_queue', 'orchestration_run', ['status', 'available_at', 'requested_at'], unique=False, schema='gis_core')
    op.create_index('uq_orchestration_schedule_occurrence', 'orchestration_run', ['schedule_id', 'scheduled_for', 'target_id'], unique=True, schema='gis_core', postgresql_nulls_not_distinct=True, postgresql_where=sa.text('schedule_id IS NOT NULL'))
    op.create_table('cost_ledger_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('data_source_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('orchestration_run_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['gis_core.data_source.id'], ),
    sa.ForeignKeyConstraint(['orchestration_run_id'], ['gis_core.orchestration_run.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['gis_core.pipeline_definition.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['gis_core.schedule_definition.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['gis_core.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orchestration_run_id', name='uq_cost_ledger_run'),
    schema='gis_core'
    )
    op.create_index('ix_cost_ledger_scope_date', 'cost_ledger_entry', ['tenant_id', 'occurred_at'], unique=False, schema='gis_core')
    op.create_table('execution_attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('orchestration_run_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.Enum('SCHEDULED', 'MANUAL', 'RETRY', 'BACKFILL', 'DEPENDENCY', name='trigger_type', schema='gis_core'), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WAITING_DEPENDENCY', 'RUNNING', 'RETRY_WAIT', 'SUCCEEDED', 'FAILED', 'BLOCKED', 'CANCELLED', name='orchestration_status', schema='gis_core'), nullable=False),
    sa.Column('worker_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingestion_run_id', sa.UUID(), nullable=True),
    sa.Column('error_classification', sa.String(length=100), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('estimated_provider_cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('actual_provider_cost', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['gis_core.ingestion_run.id'], ),
    sa.ForeignKeyConstraint(['orchestration_run_id'], ['gis_core.orchestration_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orchestration_run_id', 'attempt_number', name='uq_execution_attempt_number'),
    schema='gis_core'
    )
    op.create_index('ix_execution_attempt_status', 'execution_attempt', ['status', 'started_at'], unique=False, schema='gis_core')
    op.create_table('operational_alert',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('pipeline_id', sa.UUID(), nullable=True),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('orchestration_run_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('deduplication_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='alert_status', schema='gis_core'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['orchestration_run_id'], ['gis_core.orchestration_run.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['gis_core.pipeline_definition.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['gis_core.schedule_definition.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['gis_core.tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gis_core'
    )
    op.create_index('ix_operational_alert_tenant_status', 'operational_alert', ['tenant_id', 'status', 'opened_at'], unique=False, schema='gis_core')
    op.create_index('uq_operational_alert_open', 'operational_alert', ['tenant_id', 'deduplication_key'], unique=True, schema='gis_core', postgresql_where=sa.text("status = 'OPEN'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_operational_alert_open', table_name='operational_alert', schema='gis_core', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_index('ix_operational_alert_tenant_status', table_name='operational_alert', schema='gis_core')
    op.drop_table('operational_alert', schema='gis_core')
    op.drop_index('ix_execution_attempt_status', table_name='execution_attempt', schema='gis_core')
    op.drop_table('execution_attempt', schema='gis_core')
    op.drop_index('ix_cost_ledger_scope_date', table_name='cost_ledger_entry', schema='gis_core')
    op.drop_table('cost_ledger_entry', schema='gis_core')
    op.drop_index('uq_orchestration_schedule_occurrence', table_name='orchestration_run', schema='gis_core', postgresql_nulls_not_distinct=True, postgresql_where=sa.text('schedule_id IS NOT NULL'))
    op.drop_index('ix_orchestration_queue', table_name='orchestration_run', schema='gis_core')
    op.drop_index('ix_orchestration_history', table_name='orchestration_run', schema='gis_core')
    op.drop_table('orchestration_run', schema='gis_core')
    op.drop_index('ix_scheduled_target_tenant', table_name='scheduled_target', schema='gis_core')
    op.drop_table('scheduled_target', schema='gis_core')
    op.drop_index('uq_freshness_scope', table_name='freshness_state', schema='gis_core', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_freshness_stale', table_name='freshness_state', schema='gis_core')
    op.drop_table('freshness_state', schema='gis_core')
    op.drop_index('uq_cost_budget_scope', table_name='cost_budget', schema='gis_core', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_cost_budget_tenant', table_name='cost_budget', schema='gis_core')
    op.drop_table('cost_budget', schema='gis_core')
    op.drop_index('ix_schedule_tenant_site', table_name='schedule_definition', schema='gis_core')
    op.drop_index('ix_schedule_due', table_name='schedule_definition', schema='gis_core')
    op.drop_table('schedule_definition', schema='gis_core')
    op.drop_index('uq_pipeline_dependency_scope', table_name='pipeline_dependency', schema='gis_core', postgresql_nulls_not_distinct=True)
    op.drop_index('ix_pipeline_dependency_downstream', table_name='pipeline_dependency', schema='gis_core')
    op.drop_table('pipeline_dependency', schema='gis_core')
    op.drop_table('pipeline_definition', schema='gis_core')
    op.execute('DROP TYPE gis_core.alert_status')
    op.execute('DROP TYPE gis_core.orchestration_status')
    op.execute('DROP TYPE gis_core.trigger_type')
    op.execute('DROP TYPE gis_core.schedule_status')
    op.execute('DROP TYPE gis_core.dependency_policy')
    # ### end Alembic commands ###
