"""add strategic goals and deterministic decomposition

Revision ID: 20260902_0025
Revises: 20260902_0024
Create Date: 2026-09-02 11:13:59.400642
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260902_0025"
down_revision: Union[str, None] = "20260902_0024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decomposition_rule",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "parent_level",
            sa.Enum(
                "BUSINESS",
                "STRATEGIC_GROWTH",
                "CHANNEL_MARKET",
                "TACTICAL",
                name="objective_level",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "parent_type",
            sa.Enum(
                "REVENUE",
                "PROFITABILITY",
                "CUSTOMER_ACQUISITION",
                "LEAD_GENERATION",
                "USAGE",
                "GROWTH",
                "MARKET_POSITION",
                "RETENTION",
                "EFFICIENCY",
                "CUSTOM",
                name="objective_type",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "output_level",
            sa.Enum(
                "BUSINESS",
                "STRATEGIC_GROWTH",
                "CHANNEL_MARKET",
                "TACTICAL",
                name="objective_level",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "output_type",
            sa.Enum(
                "REVENUE",
                "PROFITABILITY",
                "CUSTOMER_ACQUISITION",
                "LEAD_GENERATION",
                "USAGE",
                "GROWTH",
                "MARKET_POSITION",
                "RETENTION",
                "EFFICIENCY",
                "CUSTOM",
                name="objective_type",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column("formula", sa.Text(), nullable=False),
        sa.Column("required_metrics_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("supported_units_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_metric_key", sa.String(length=100), nullable=False),
        sa.Column("assumptions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("readiness_policy_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "rights_requirements_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("approval_required", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", "version", name="uq_decomposition_rule_version"),
        schema="gis_core",
    )
    op.create_table(
        "strategic_objective",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "level",
            sa.Enum(
                "BUSINESS",
                "STRATEGIC_GROWTH",
                "CHANNEL_MARKET",
                "TACTICAL",
                name="objective_level",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "objective_type",
            sa.Enum(
                "REVENUE",
                "PROFITABILITY",
                "CUSTOMER_ACQUISITION",
                "LEAD_GENERATION",
                "USAGE",
                "GROWTH",
                "MARKET_POSITION",
                "RETENTION",
                "EFFICIENCY",
                "CUSTOM",
                name="objective_type",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "lifecycle",
            sa.Enum(
                "DRAFT",
                "PROPOSED",
                "ACTIVE",
                "PAUSED",
                "ACHIEVED",
                "MISSED",
                "CANCELLED",
                "ARCHIVED",
                name="objective_lifecycle",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "USER_DEFINED",
                "DETERMINISTIC",
                "STATISTICAL",
                "AI_PROPOSED",
                "IMPORTED",
                "USER_OVERRIDE",
                name="objective_origin",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "approval_state",
            sa.Enum(
                "NOT_REQUIRED",
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="objective_approval",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "progress_state",
            sa.Enum(
                "NOT_STARTED",
                "AHEAD",
                "ON_TRACK",
                "BEHIND",
                "AT_RISK",
                "ACHIEVED",
                "MISSED",
                "UNKNOWN",
                name="objective_progress",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "measurement_health",
            sa.Enum(
                "MEASURABLE",
                "NOT_YET_MEASURABLE",
                "INSUFFICIENT_DATA",
                "STALE_DATA",
                "BLOCKED_SOURCE",
                "BLOCKED_RIGHTS",
                "UNSUPPORTED_METRIC",
                name="objective_measurement_health",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "decomposition_state",
            sa.Enum(
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETE",
                "PARTIAL",
                "BLOCKED_MISSING_DATA",
                "BLOCKED_UNSUPPORTED_METRIC",
                "BLOCKED_RIGHTS",
                "BLOCKED_STALE_DATA",
                "AWAITING_APPROVAL",
                name="decomposition_state",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("scope_type", sa.String(length=50), nullable=False),
        sa.Column("scope_key", sa.Text(), nullable=True),
        sa.Column("scope_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_objective_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "origin NOT IN ('STATISTICAL', 'AI_PROPOSED') OR lifecycle IN ('DRAFT', 'PROPOSED')",
            name="ck_objective_non_authoritative_origin",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_objective_id"],
            ["gis_core.strategic_objective.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gis_core",
    )
    op.create_index(
        "ix_strategic_objective_attention",
        "strategic_objective",
        ["measurement_health", "decomposition_state"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_strategic_objective_scope",
        "strategic_objective",
        ["tenant_id", "site_id", "lifecycle"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "decomposition_plan",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("objective_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "CANDIDATE",
                "AWAITING_APPROVAL",
                "APPROVED",
                "REJECTED",
                "SUPERSEDED",
                name="decomposition_plan_status",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "USER_DEFINED",
                "DETERMINISTIC",
                "STATISTICAL",
                "AI_PROPOSED",
                "IMPORTED",
                "USER_OVERRIDE",
                name="objective_origin",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("provenance_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["objective_id"], ["gis_core.strategic_objective.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["gis_core.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gis_core",
    )
    op.create_index(
        "ix_decomposition_plan_objective",
        "decomposition_plan",
        ["objective_id", "status"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "objective_audit_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("objective_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("before_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("after_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["objective_id"], ["gis_core.strategic_objective.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["gis_core.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gis_core",
    )
    op.create_index(
        "ix_objective_audit_history",
        "objective_audit_event",
        ["objective_id", "occurred_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "objective_relationship",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("source_objective_id", sa.UUID(), nullable=False),
        sa.Column("target_objective_id", sa.UUID(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "SUPPORTS",
                "DEPENDS_ON",
                "CONSTRAINS",
                "CONFLICTS_WITH",
                name="objective_relationship_type",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source_objective_id <> target_objective_id", name="ck_objective_no_self_edge"
        ),
        sa.ForeignKeyConstraint(
            ["source_objective_id"], ["gis_core.strategic_objective.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_objective_id"], ["gis_core.strategic_objective.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["gis_core.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "source_objective_id",
            "target_objective_id",
            "relationship_type",
            name="uq_objective_relationship",
        ),
        schema="gis_core",
    )
    op.create_index(
        "ix_objective_relationship_source",
        "objective_relationship",
        ["source_objective_id"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_objective_relationship_target",
        "objective_relationship",
        ["target_objective_id"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "objective_target",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("objective_id", sa.UUID(), nullable=False),
        sa.Column("metric_definition_id", sa.UUID(), nullable=False),
        sa.Column(
            "family",
            sa.Enum(
                "ABSOLUTE_METRIC",
                "RELATIVE_CHANGE",
                "RANK",
                "COMPETITIVE",
                "MARKET",
                "FUNNEL",
                "FINANCIAL",
                "GUARDRAIL",
                name="target_family",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "direction",
            sa.Enum(
                "AT_LEAST",
                "AT_MOST",
                "BETWEEN",
                "INCREASE_BY",
                "DECREASE_BY",
                "RANK_AT_OR_ABOVE",
                "OUTRANK_ENTITY",
                name="target_direction",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=100), nullable=False),
        sa.Column("target_value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("target_upper_value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("condition_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("baseline_value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("baseline_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("baseline_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("measurement_window", sa.String(length=100), nullable=True),
        sa.Column("aggregation", sa.String(length=50), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("entity_scope_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "measurement_binding_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "measurement_health",
            sa.Enum(
                "MEASURABLE",
                "NOT_YET_MEASURABLE",
                "INSUFFICIENT_DATA",
                "STALE_DATA",
                "BLOCKED_SOURCE",
                "BLOCKED_RIGHTS",
                "UNSUPPORTED_METRIC",
                name="objective_measurement_health",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "approval_state",
            sa.Enum(
                "NOT_REQUIRED",
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="objective_approval",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "USER_DEFINED",
                "DETERMINISTIC",
                "STATISTICAL",
                "AI_PROPOSED",
                "IMPORTED",
                "USER_OVERRIDE",
                name="objective_origin",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column("suggested_value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("override_rationale", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "target_value IS NOT NULL OR condition_json <> '{}'::jsonb", name="ck_target_condition"
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["gis_core.intervention_metric_definition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["objective_id"], ["gis_core.strategic_objective.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["gis_core.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gis_core",
    )
    op.create_index(
        "ix_objective_target_objective",
        "objective_target",
        ["objective_id", "measurement_health"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "objective_derivation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("decomposition_plan_id", sa.UUID(), nullable=False),
        sa.Column("source_objective_id", sa.UUID(), nullable=False),
        sa.Column("generated_objective_id", sa.UUID(), nullable=True),
        sa.Column("generated_target_id", sa.UUID(), nullable=True),
        sa.Column("rule_id", sa.UUID(), nullable=False),
        sa.Column("rule_key", sa.String(length=100), nullable=False),
        sa.Column("rule_version", sa.String(length=50), nullable=False),
        sa.Column("formula", sa.Text(), nullable=False),
        sa.Column("required_inputs_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("input_values_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column(
            "source_references_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("assumptions_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rights_state", sa.String(length=50), nullable=False),
        sa.Column("readiness_state", sa.String(length=50), nullable=False),
        sa.Column(
            "result_status",
            sa.Enum(
                "CURRENT",
                "BLOCKED",
                "SUPERSEDED",
                "REJECTED",
                name="derivation_result_status",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("supersedes_derivation_id", sa.UUID(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["decomposition_plan_id"],
            ["gis_core.decomposition_plan.id"],
        ),
        sa.ForeignKeyConstraint(
            ["generated_objective_id"],
            ["gis_core.strategic_objective.id"],
        ),
        sa.ForeignKeyConstraint(
            ["generated_target_id"],
            ["gis_core.objective_target.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["gis_core.decomposition_rule.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_objective_id"],
            ["gis_core.strategic_objective.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_derivation_id"],
            ["gis_core.objective_derivation.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["gis_core.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_hash", name="uq_objective_derivation_identity"),
        schema="gis_core",
    )
    op.create_index(
        "ix_objective_derivation_parent",
        "objective_derivation",
        ["source_objective_id", "executed_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "objective_measurement",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("unit", sa.String(length=100), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("data_asset_id", sa.UUID(), nullable=True),
        sa.Column("source_reference", sa.Text(), nullable=True),
        sa.Column("rights_policy_id", sa.UUID(), nullable=True),
        sa.Column("freshness_state", sa.String(length=50), nullable=False),
        sa.Column("readiness_state", sa.String(length=50), nullable=False),
        sa.Column("method_key", sa.String(length=100), nullable=False),
        sa.Column("method_version", sa.String(length=50), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_asset_id"],
            ["gis_core.data_asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rights_policy_id"],
            ["gis_core.data_rights_policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"], ["gis_core.objective_target.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["gis_core.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_hash", name="uq_objective_measurement_identity"),
        schema="gis_core",
    )
    op.create_index(
        "ix_objective_measurement_target",
        "objective_measurement",
        ["target_id", "measured_at"],
        unique=False,
        schema="gis_core",
    )
    op.add_column(
        "intervention_metric_definition",
        sa.Column("description", sa.Text(), nullable=True),
        schema="gis_core",
    )
    op.add_column(
        "intervention_metric_definition",
        sa.Column("domain", sa.String(length=100), nullable=True),
        schema="gis_core",
    )
    op.add_column(
        "intervention_metric_definition",
        sa.Column("directionality", sa.String(length=50), nullable=True),
        schema="gis_core",
    )
    op.add_column(
        "intervention_metric_definition",
        sa.Column("aggregation", sa.String(length=50), nullable=True),
        schema="gis_core",
    )
    op.add_column(
        "intervention_metric_definition",
        sa.Column(
            "supported_scopes_json",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        schema="gis_core",
    )
    op.add_column(
        "intervention_metric_definition",
        sa.Column("authoritative_asset_id", sa.UUID(), nullable=True),
        schema="gis_core",
    )
    op.add_column(
        "intervention_metric_definition",
        sa.Column("currently_measurable", sa.Boolean(), server_default=sa.false(), nullable=False),
        schema="gis_core",
    )
    op.add_column(
        "intervention_metric_definition",
        sa.Column("derived", sa.Boolean(), server_default=sa.false(), nullable=False),
        schema="gis_core",
    )
    op.add_column(
        "intervention_metric_definition",
        sa.Column("freshness_expectation_seconds", sa.Integer(), nullable=True),
        schema="gis_core",
    )
    op.create_foreign_key(
        "fk_metric_authoritative_asset",
        "intervention_metric_definition",
        "data_asset",
        ["authoritative_asset_id"],
        ["id"],
        source_schema="gis_core",
        referent_schema="gis_core",
    )
    op.execute("""
        INSERT INTO gis_core.intervention_metric_definition
          (id, key, version, name, source_system, unit, grain, enabled,
           description, domain, directionality, aggregation, supported_scopes_json,
           currently_measurable, derived)
        VALUES
          (gen_random_uuid(), 'GA4_USERS', '1', 'GA4 users', 'GA4', 'count', 'objective_window', true, 'Governed objective metric: GA4 users.', 'TRAFFIC', 'HIGHER_IS_BETTER', 'SUM', '["SITE","CHANNEL"]', true, false),
          (gen_random_uuid(), 'QUERY_RANK', '1', 'Observed query rank', 'SERP', 'rank', 'objective_window', true, 'Governed objective metric: observed query rank.', 'SEARCH', 'LOWER_IS_BETTER', 'LATEST', '["QUERY","URL"]', true, false),
          (gen_random_uuid(), 'SEARCH_VISIBILITY_SHARE', '1', 'Search visibility share', 'MARKET_INTELLIGENCE', 'ratio', 'objective_window', true, 'Governed objective metric: search visibility share.', 'MARKET', 'HIGHER_IS_BETTER', 'MODEL', '["MARKET","DOMAIN"]', true, false),
          (gen_random_uuid(), 'MONTHLY_REVENUE', '1', 'Monthly revenue', 'FINANCIAL', 'currency', 'objective_window', true, 'Future financial metric; no authoritative binding exists.', 'FINANCIAL', 'HIGHER_IS_BETTER', 'SUM', '["SITE"]', false, false),
          (gen_random_uuid(), 'REVENUE_PER_VISITOR', '1', 'Revenue per qualified visitor', 'FINANCIAL', 'currency_per_visitor', 'objective_window', true, 'Future financial metric; no authoritative binding exists.', 'FINANCIAL', 'HIGHER_IS_BETTER', 'RATIO', '["SITE"]', false, false),
          (gen_random_uuid(), 'REQUIRED_QUALIFIED_VISITORS', '1', 'Required qualified visitors', 'GIS_DETERMINISTIC', 'visitors', 'objective_window', true, 'Deterministic output metric.', 'TRAFFIC', 'HIGHER_IS_BETTER', 'SUM', '["SITE","CHANNEL"]', false, true)
        ON CONFLICT (key, version) DO NOTHING
    """)
    op.execute("""
        UPDATE gis_core.intervention_metric_definition SET
          description = COALESCE(description, 'Governed metric usable by interventions and strategic objectives.'),
          domain = COALESCE(domain, CASE WHEN key LIKE 'GSC_%' THEN 'SEARCH' WHEN key LIKE 'GA4_%' THEN 'TRAFFIC' WHEN key LIKE 'CRUX_%' THEN 'EXPERIENCE' ELSE 'GOVERNANCE' END),
          directionality = COALESCE(directionality, CASE WHEN key IN ('GSC_POSITION','CRUX_LCP','CRUX_INP','CRUX_CLS') THEN 'LOWER_IS_BETTER' ELSE 'HIGHER_IS_BETTER' END),
          aggregation = COALESCE(aggregation, CASE WHEN unit IN ('ratio','percent') THEN 'WEIGHTED_RATE' ELSE 'SUM' END),
          supported_scopes_json = CASE WHEN supported_scopes_json = '[]'::jsonb THEN '["SITE"]'::jsonb ELSE supported_scopes_json END,
          currently_measurable = CASE WHEN key LIKE 'GSC_%' OR key LIKE 'GA4_%' THEN true ELSE currently_measurable END
    """)
    op.execute("""
        INSERT INTO gis_core.decomposition_rule
          (id, key, version, name, description, parent_level, parent_type,
           output_level, output_type, formula, required_metrics_json,
           supported_units_json, output_metric_key, assumptions_json,
           readiness_policy_json, rights_requirements_json, approval_required,
           enabled, created_at, updated_at)
        VALUES
          (gen_random_uuid(), 'REVENUE_TO_REQUIRED_TRAFFIC', '1',
           'Revenue to required qualified traffic',
           'Divides an explicit revenue target by an authoritative revenue-per-qualified-visitor measurement.',
           'BUSINESS', 'REVENUE', 'STRATEGIC_GROWTH', 'GROWTH',
           'monthly_revenue_target / revenue_per_qualified_visitor',
           '["MONTHLY_REVENUE","REVENUE_PER_VISITOR"]',
           '["currency","currency_per_visitor","visitors"]',
           'REQUIRED_QUALIFIED_VISITORS', '[]',
           jsonb_build_object('require_current', true, 'stale_inputs_allowed', false),
           '["deterministic_analysis_allowed","derived_storage_allowed"]',
           true, true, now(), now())
        ON CONFLICT (key, version) DO NOTHING
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_metric_authoritative_asset",
        "intervention_metric_definition",
        schema="gis_core",
        type_="foreignkey",
    )
    op.drop_column(
        "intervention_metric_definition", "freshness_expectation_seconds", schema="gis_core"
    )
    op.drop_column("intervention_metric_definition", "derived", schema="gis_core")
    op.drop_column("intervention_metric_definition", "currently_measurable", schema="gis_core")
    op.drop_column("intervention_metric_definition", "authoritative_asset_id", schema="gis_core")
    op.drop_column("intervention_metric_definition", "supported_scopes_json", schema="gis_core")
    op.drop_column("intervention_metric_definition", "aggregation", schema="gis_core")
    op.drop_column("intervention_metric_definition", "directionality", schema="gis_core")
    op.drop_column("intervention_metric_definition", "domain", schema="gis_core")
    op.drop_column("intervention_metric_definition", "description", schema="gis_core")
    op.drop_index(
        "ix_objective_measurement_target", table_name="objective_measurement", schema="gis_core"
    )
    op.drop_table("objective_measurement", schema="gis_core")
    op.drop_index(
        "ix_objective_derivation_parent", table_name="objective_derivation", schema="gis_core"
    )
    op.drop_table("objective_derivation", schema="gis_core")
    op.drop_index("ix_objective_target_objective", table_name="objective_target", schema="gis_core")
    op.drop_table("objective_target", schema="gis_core")
    op.drop_index(
        "ix_objective_relationship_target", table_name="objective_relationship", schema="gis_core"
    )
    op.drop_index(
        "ix_objective_relationship_source", table_name="objective_relationship", schema="gis_core"
    )
    op.drop_table("objective_relationship", schema="gis_core")
    op.drop_index(
        "ix_objective_audit_history", table_name="objective_audit_event", schema="gis_core"
    )
    op.drop_table("objective_audit_event", schema="gis_core")
    op.drop_index(
        "ix_decomposition_plan_objective", table_name="decomposition_plan", schema="gis_core"
    )
    op.drop_table("decomposition_plan", schema="gis_core")
    op.drop_index(
        "ix_strategic_objective_scope", table_name="strategic_objective", schema="gis_core"
    )
    op.drop_index(
        "ix_strategic_objective_attention", table_name="strategic_objective", schema="gis_core"
    )
    op.drop_table("strategic_objective", schema="gis_core")
    op.drop_table("decomposition_rule", schema="gis_core")
    for name in (
        "derivation_result_status",
        "target_direction",
        "target_family",
        "objective_relationship_type",
        "decomposition_plan_status",
        "decomposition_state",
        "objective_measurement_health",
        "objective_progress",
        "objective_approval",
        "objective_origin",
        "objective_lifecycle",
        "objective_type",
        "objective_level",
    ):
        op.execute(sa.text(f"DROP TYPE IF EXISTS gis_core.{name}"))
    # ### end Alembic commands ###
