"""add ai recommendation engine

Revision ID: 20260831_0021
Revises: 20260831_0020
Create Date: 2026-08-31 12:50:04.546035
"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '20260831_0021'
down_revision: Union[str, None] = '20260831_0020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _enum(name: str) -> postgresql.ENUM:
    return postgresql.ENUM(name=name, schema="gis_core", create_type=False)


def upgrade() -> None:
    bind = op.get_bind()
    definitions = {
        "recommendation_run_status": ["PENDING", "RUNNING", "SUCCEEDED", "NO_VALID_RECOMMENDATION", "BLOCKED", "FAILED"],
        "recommendation_status": ["DRAFT", "GENERATED", "VALIDATED", "READY_FOR_REVIEW", "ACCEPTED", "PARTIALLY_ACCEPTED", "REJECTED", "SUPERSEDED", "EXPIRED", "INVALIDATED"],
        "candidate_validation_state": ["VALID", "INVALID", "BLOCKED"],
        "recommendation_review_decision": ["ACCEPT", "PARTIAL_ACCEPT", "REJECT", "REQUEST_REGENERATION"],
    }
    for name, values in definitions.items():
        postgresql.ENUM(*values, name=name, schema="gis_core").create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_policy',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('provider_key', sa.String(length=100), nullable=False),
    sa.Column('model_identifier', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('policy_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'version', name='uq_recommendation_policy_version'),
    schema='gis_core'
    )
    op.create_table('recommendation_run',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('recommendation_policy_id', sa.UUID(), nullable=False),
    sa.Column('status', _enum('recommendation_run_status'), nullable=False),
    sa.Column('provider_key', sa.String(length=100), nullable=False),
    sa.Column('model_identifier', sa.String(length=255), nullable=False),
    sa.Column('model_configuration_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('provider_cost', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('validation_errors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('repair_attempts', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['gis_core.opportunity.id'], ),
    sa.ForeignKeyConstraint(['recommendation_policy_id'], ['gis_core.recommendation_policy.id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'site_id'], ['gis_core.site.tenant_id', 'gis_core.site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('context_hash', name='uq_recommendation_run_context'),
    schema='gis_core'
    )
    op.create_index('ix_recommendation_run_scope', 'recommendation_run', ['tenant_id', 'site_id', 'started_at'], unique=False, schema='gis_core')
    op.create_table('recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('analytical_entity_id', sa.UUID(), nullable=False),
    sa.Column('market_definition_id', sa.UUID(), nullable=True),
    sa.Column('market_definition_version', sa.Integer(), nullable=True),
    sa.Column('status', _enum('recommendation_status'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('assumptions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analytical_entity_id'], ['gis_core.analytical_entity.id'], ),
    sa.ForeignKeyConstraint(['market_definition_id'], ['gis_core.market_definition.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['gis_core.opportunity.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['gis_core.recommendation_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_hash', name='uq_recommendation_identity'),
    schema='gis_core'
    )
    op.create_index('ix_recommendation_scope', 'recommendation', ['tenant_id', 'site_id', 'status'], unique=False, schema='gis_core')
    op.create_table('recommendation_candidate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('intervention_type_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('fit', sa.String(length=50), nullable=False),
    sa.Column('validation_state', _enum('candidate_validation_state'), nullable=False),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_metric_key', sa.String(length=100), nullable=False),
    sa.Column('expected_direction', _enum('expected_direction'), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('assumptions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limitations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('feasibility', _enum('feasibility_state'), nullable=False),
    sa.Column('measurement_readiness', _enum('measurement_readiness'), nullable=False),
    sa.Column('validation_errors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accepted_intervention_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_intervention_id'], ['gis_core.intervention.id'], ),
    sa.ForeignKeyConstraint(['intervention_type_id'], ['gis_core.intervention_type_definition.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['gis_core.recommendation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', 'rank', name='uq_recommendation_candidate_rank'),
    schema='gis_core'
    )
    op.create_table('recommendation_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('evidence_package_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_package_id'], ['gis_core.evidence_package.id'], ),
    sa.ForeignKeyConstraint(['recommendation_id'], ['gis_core.recommendation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recommendation_id', 'evidence_package_id', name='uq_recommendation_evidence'),
    schema='gis_core'
    )
    op.create_table('recommendation_review',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=False),
    sa.Column('decision', _enum('recommendation_review_decision'), nullable=False),
    sa.Column('reviewer', sa.String(length=255), nullable=False),
    sa.Column('reason_category', sa.String(length=100), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('accepted_candidate_ids_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['gis_core.recommendation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='gis_core'
    )
    op.create_index('ix_recommendation_review_history', 'recommendation_review', ['recommendation_id', 'reviewed_at'], unique=False, schema='gis_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for view in (
        "stg_recommendation_reviews",
        "stg_recommendation_candidates",
        "stg_recommendations",
        "stg_recommendation_runs",
    ):
        op.execute(f"DROP VIEW IF EXISTS gis_staging.{view} CASCADE")
    op.drop_index('ix_recommendation_review_history', table_name='recommendation_review', schema='gis_core')
    op.drop_table('recommendation_review', schema='gis_core')
    op.drop_table('recommendation_evidence', schema='gis_core')
    op.drop_table('recommendation_candidate', schema='gis_core')
    op.drop_index('ix_recommendation_scope', table_name='recommendation', schema='gis_core')
    op.drop_table('recommendation', schema='gis_core')
    op.drop_index('ix_recommendation_run_scope', table_name='recommendation_run', schema='gis_core')
    op.drop_table('recommendation_run', schema='gis_core')
    op.drop_table('recommendation_policy', schema='gis_core')
    bind = op.get_bind()
    for name in (
        "recommendation_review_decision",
        "candidate_validation_state",
        "recommendation_status",
        "recommendation_run_status",
    ):
        postgresql.ENUM(name=name, schema="gis_core").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
