"""add authority intelligence

Revision ID: 20260830_0014
Revises: 20260830_0013
Create Date: 2026-08-30 16:35:04.048452
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260830_0014"
down_revision: Union[str, None] = "20260830_0013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _enum(name: str) -> postgresql.ENUM:
    return postgresql.ENUM(name=name, schema="gis_core", create_type=False)


def upgrade() -> None:
    bind = op.get_bind()
    enum_definitions = {
        "authority_target_type": ["DOMAIN", "PAGE"],
        "authority_ownership": ["OWNED", "COMPETITOR", "OTHER", "UNKNOWN"],
        "authority_link_state": ["OBSERVED_ACTIVE", "OBSERVED_NEW", "OBSERVED_LOST", "UNKNOWN"],
        "authority_follow_state": ["FOLLOWED", "NOFOLLOW", "UNKNOWN"],
        "authority_link_type": ["TEXT", "IMAGE", "REDIRECT", "OTHER", "UNKNOWN"],
        "anchor_classification": [
            "BRAND",
            "EXACT_MATCH",
            "PARTIAL_MATCH",
            "URL",
            "GENERIC",
            "IMAGE_OR_EMPTY",
            "OTHER",
            "UNKNOWN",
        ],
    }
    for name, values in enum_definitions.items():
        postgresql.ENUM(*values, name=name, schema="gis_core").create(bind, checkfirst=True)
    op.execute("ALTER TYPE gis_core.competitive_event_domain ADD VALUE IF NOT EXISTS 'AUTHORITY'")
    for value in (
        "BACKLINK_FIRST_OBSERVED",
        "BACKLINK_GAINED",
        "BACKLINK_LOST",
        "REFERRING_DOMAIN_FIRST_OBSERVED",
        "REFERRING_DOMAIN_GAINED",
        "REFERRING_DOMAIN_LOST",
        "AUTHORITY_METRIC_INCREASED",
        "AUTHORITY_METRIC_DECREASED",
        "REFERRING_DOMAIN_VELOCITY_CHANGED",
    ):
        op.execute(f"ALTER TYPE gis_core.competitive_event_type ADD VALUE IF NOT EXISTS '{value}'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authority_metric_definition",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("metric_key", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scale_min", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("scale_max", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("methodology_version", sa.String(length=100), nullable=True),
        sa.Column(
            "semantic_class",
            _enum("event_semantic_class"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "metric_key", name="uq_authority_metric_provider_key"),
        schema="gis_core",
    )
    op.create_table(
        "authority_observation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("data_source_connection_id", sa.UUID(), nullable=False),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=False),
        sa.Column("rights_policy_id", sa.UUID(), nullable=False),
        sa.Column("rights_policy_version", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("provider_task_id", sa.String(length=255), nullable=True),
        sa.Column(
            "target_type",
            _enum("authority_target_type"),
            nullable=False,
        ),
        sa.Column("target_domain", sa.String(length=253), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=True),
        sa.Column(
            "ownership",
            _enum("authority_ownership"),
            nullable=False,
        ),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observation_scope", sa.String(length=100), nullable=False),
        sa.Column("completeness", sa.String(length=50), nullable=False),
        sa.Column("observation_key", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("request_count", sa.Integer(), nullable=False),
        sa.Column("records_received", sa.Integer(), nullable=False),
        sa.Column("provider_reported_cost", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("cost_currency", sa.String(length=3), nullable=False),
        sa.Column("provider_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_end IS NULL OR effective_end >= effective_start",
            name="ck_authority_observation_effective_window",
        ),
        sa.ForeignKeyConstraint(
            ["data_source_connection_id"],
            ["gis_core.data_source_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["gis_core.organization.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rights_policy_id"],
            ["gis_core.data_rights_policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "ingestion_run_id"],
            [
                "gis_core.ingestion_run.tenant_id",
                "gis_core.ingestion_run.site_id",
                "gis_core.ingestion_run.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gis_raw",
    )
    op.create_index(
        "ix_authority_observation_run",
        "authority_observation",
        ["ingestion_run_id"],
        unique=False,
        schema="gis_raw",
    )
    op.create_index(
        "ix_authority_observation_target_date",
        "authority_observation",
        ["tenant_id", "site_id", "target_domain", "observed_at"],
        unique=False,
        schema="gis_raw",
    )
    op.create_index(
        "uq_authority_observation_current",
        "authority_observation",
        ["observation_key"],
        unique=True,
        schema="gis_raw",
        postgresql_where=sa.text("effective_end IS NULL"),
    )
    op.create_table(
        "authority_metric_observation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("authority_observation_id", sa.UUID(), nullable=False),
        sa.Column("metric_definition_id", sa.UUID(), nullable=True),
        sa.Column("metric_provider", sa.String(length=100), nullable=False),
        sa.Column("metric_key", sa.String(length=150), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column("metric_value", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("scale_min", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("scale_max", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("methodology_version", sa.String(length=100), nullable=True),
        sa.Column(
            "semantic_class",
            _enum("event_semantic_class"),
            nullable=False,
        ),
        sa.Column("provider_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "scale_max IS NULL OR scale_min IS NULL OR scale_max >= scale_min",
            name="ck_authority_metric_scale",
        ),
        sa.ForeignKeyConstraint(
            ["authority_observation_id"], ["gis_raw.authority_observation.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["gis_core.authority_metric_definition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "authority_observation_id",
            "metric_provider",
            "metric_key",
            name="uq_authority_metric_observation",
        ),
        schema="gis_raw",
    )
    op.create_index(
        "ix_authority_metric_key",
        "authority_metric_observation",
        ["metric_provider", "metric_key"],
        unique=False,
        schema="gis_raw",
    )
    op.create_table(
        "backlink_observation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("authority_observation_id", sa.UUID(), nullable=False),
        sa.Column("provider_record_id", sa.String(length=512), nullable=True),
        sa.Column("link_identity", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_domain", sa.String(length=253), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=False),
        sa.Column("target_domain", sa.String(length=253), nullable=False),
        sa.Column(
            "link_state",
            _enum("authority_link_state"),
            nullable=False,
        ),
        sa.Column(
            "follow_state",
            _enum("authority_follow_state"),
            nullable=False,
        ),
        sa.Column("sponsored", sa.Boolean(), nullable=True),
        sa.Column("ugc", sa.Boolean(), nullable=True),
        sa.Column(
            "link_type",
            _enum("authority_link_type"),
            nullable=False,
        ),
        sa.Column("anchor_text", sa.Text(), nullable=True),
        sa.Column("anchor_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "anchor_classification",
            _enum("anchor_classification"),
            nullable=False,
        ),
        sa.Column("anchor_method", sa.String(length=100), nullable=True),
        sa.Column("anchor_method_version", sa.String(length=32), nullable=True),
        sa.Column("anchor_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "semantic_class",
            _enum("event_semantic_class"),
            nullable=False,
        ),
        sa.Column("provider_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["authority_observation_id"], ["gis_raw.authority_observation.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "authority_observation_id", "link_identity", name="uq_backlink_observation_identity"
        ),
        schema="gis_raw",
    )
    op.create_index(
        "ix_backlink_source_domain",
        "backlink_observation",
        ["source_domain"],
        unique=False,
        schema="gis_raw",
    )
    op.create_index(
        "ix_backlink_state", "backlink_observation", ["link_state"], unique=False, schema="gis_raw"
    )
    op.create_index(
        "ix_backlink_target_domain",
        "backlink_observation",
        ["target_domain"],
        unique=False,
        schema="gis_raw",
    )
    op.create_index(
        "ix_backlink_target_url",
        "backlink_observation",
        ["target_url"],
        unique=False,
        schema="gis_raw",
    )
    op.create_table(
        "referring_domain_observation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("authority_observation_id", sa.UUID(), nullable=False),
        sa.Column("referring_domain", sa.String(length=253), nullable=False),
        sa.Column("target_domain", sa.String(length=253), nullable=False),
        sa.Column("backlink_count", sa.Integer(), nullable=False),
        sa.Column("followed_count", sa.Integer(), nullable=False),
        sa.Column("nofollow_count", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "link_state",
            _enum("authority_link_state"),
            nullable=False,
        ),
        sa.Column(
            "semantic_class",
            _enum("event_semantic_class"),
            nullable=False,
        ),
        sa.Column("provider_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["authority_observation_id"], ["gis_raw.authority_observation.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "authority_observation_id", "referring_domain", name="uq_referring_domain_observation"
        ),
        schema="gis_raw",
    )
    op.create_index(
        "ix_referring_domain_target",
        "referring_domain_observation",
        ["referring_domain", "target_domain"],
        unique=False,
        schema="gis_raw",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # dbt staging views directly depend on these tables. Only Epic 20 views are removed.
    op.execute("DROP VIEW IF EXISTS gis_staging.stg_referring_domain_observations CASCADE")
    op.execute("DROP VIEW IF EXISTS gis_staging.stg_backlink_observations CASCADE")
    op.execute("DROP VIEW IF EXISTS gis_staging.stg_authority_metric_observations CASCADE")
    op.execute("DROP VIEW IF EXISTS gis_staging.stg_authority_observations CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_referring_domain_target", table_name="referring_domain_observation", schema="gis_raw"
    )
    op.drop_table("referring_domain_observation", schema="gis_raw")
    op.drop_index("ix_backlink_target_url", table_name="backlink_observation", schema="gis_raw")
    op.drop_index("ix_backlink_target_domain", table_name="backlink_observation", schema="gis_raw")
    op.drop_index("ix_backlink_state", table_name="backlink_observation", schema="gis_raw")
    op.drop_index("ix_backlink_source_domain", table_name="backlink_observation", schema="gis_raw")
    op.drop_table("backlink_observation", schema="gis_raw")
    op.drop_index(
        "ix_authority_metric_key", table_name="authority_metric_observation", schema="gis_raw"
    )
    op.drop_table("authority_metric_observation", schema="gis_raw")
    op.drop_index(
        "uq_authority_observation_current",
        table_name="authority_observation",
        schema="gis_raw",
        postgresql_where=sa.text("effective_end IS NULL"),
    )
    op.drop_index(
        "ix_authority_observation_target_date", table_name="authority_observation", schema="gis_raw"
    )
    op.drop_index(
        "ix_authority_observation_run", table_name="authority_observation", schema="gis_raw"
    )
    op.drop_table("authority_observation", schema="gis_raw")
    op.drop_table("authority_metric_definition", schema="gis_core")
    bind = op.get_bind()
    for name in (
        "anchor_classification",
        "authority_link_type",
        "authority_follow_state",
        "authority_link_state",
        "authority_ownership",
        "authority_target_type",
    ):
        postgresql.ENUM(name=name, schema="gis_core").drop(bind, checkfirst=True)
    # PostgreSQL enum values on the existing Epic 19 types remain reserved after downgrade.
    # ### end Alembic commands ###
