"""add evidence quality identity resolution

Revision ID: 20260831_0018
Revises: 20260831_0017
Create Date: 2026-08-31 07:52:41.300163
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260831_0018"
down_revision: Union[str, None] = "20260831_0017"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _enum(name: str) -> postgresql.ENUM:
    return postgresql.ENUM(name=name, schema="gis_core", create_type=False)


def upgrade() -> None:
    bind = op.get_bind()
    enums = {
        "analytical_entity_type": [
            "SITE",
            "DOMAIN",
            "URL",
            "QUERY",
            "TOPIC",
            "MARKET",
            "MARKET_SEGMENT",
        ],
        "identity_relationship": [
            "SAME_ENTITY",
            "ALIAS_OF",
            "CANONICAL_OF",
            "REDIRECTS_TO",
            "SUBDOMAIN_OF",
            "SAME_REGISTRABLE_DOMAIN",
            "MEMBER_OF",
            "RELATED_NOT_IDENTICAL",
        ],
        "resolution_strength": [
            "EXACT",
            "STRONG",
            "SUPPORTED",
            "WEAK",
            "UNRESOLVED",
            "CONFLICTING",
        ],
        "assertion_status": ["ACTIVE", "SUPERSEDED", "REJECTED"],
        "source_independence_state": [
            "SAME_ROOT_SOURCE",
            "DEPENDENT_DERIVATION",
            "PARTIALLY_INDEPENDENT",
            "INDEPENDENT",
            "UNKNOWN",
        ],
        "corroboration_state": [
            "UNSUPPORTED",
            "SINGLE_SOURCE",
            "CORROBORATED",
            "MULTI_SOURCE_CORROBORATED",
            "CONFLICTING",
            "INSUFFICIENT",
        ],
        "rights_usability": ["USABLE", "BLOCKED", "PARTIALLY_USABLE", "UNKNOWN"],
        "evidence_compatibility": ["COMPATIBLE", "PARTIALLY_COMPATIBLE", "INCOMPATIBLE", "UNKNOWN"],
        "quality_dimension_type": [
            "IDENTITY_RESOLUTION",
            "FRESHNESS",
            "COMPLETENESS",
            "TEMPORAL_CONTINUITY",
            "PROVENANCE_COMPLETENESS",
            "SOURCE_INDEPENDENCE",
            "CROSS_SOURCE_CORROBORATION",
            "CONSISTENCY",
            "METHOD_COMPATIBILITY",
            "SCOPE_COMPATIBILITY",
            "RIGHTS_USABILITY",
        ],
        "quality_dimension_state": [
            "UNKNOWN",
            "NOT_APPLICABLE",
            "BLOCKED",
            "LIMITED",
            "SUPPORTED",
            "STRONG",
        ],
    }
    for name, values in enums.items():
        postgresql.ENUM(*values, name=name, schema="gis_core").create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evidence_contract",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("contract_key", sa.String(length=100), nullable=False),
        sa.Column("contract_version", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("requirements_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "contract_key", "contract_version", name="uq_evidence_contract_version"
        ),
        schema="gis_core",
    )
    op.create_table(
        "analytical_entity",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("entity_type", _enum("analytical_entity_type"), nullable=False),
        sa.Column("canonical_key", sa.Text(), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("device", sa.String(length=32), nullable=True),
        sa.Column("method_key", sa.String(length=100), nullable=False),
        sa.Column("method_version", sa.String(length=50), nullable=False),
        sa.Column("source_reference_type", sa.String(length=100), nullable=True),
        sa.Column("source_reference_id", sa.UUID(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "site_id", "identity_hash", name="uq_analytical_entity"),
        schema="gis_core",
    )
    op.create_index(
        "ix_analytical_entity_scope",
        "analytical_entity",
        ["tenant_id", "site_id", "entity_type"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "evidence_quality_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("method_version", sa.String(length=50), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("input_count", sa.Integer(), nullable=False),
        sa.Column("package_count", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "site_id", "fingerprint", name="uq_evidence_quality_run"),
        schema="gis_core",
    )
    op.create_index(
        "ix_evidence_quality_run_scope",
        "evidence_quality_run",
        ["tenant_id", "site_id", "assessed_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "identity_assertion",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("subject_entity_id", sa.UUID(), nullable=False),
        sa.Column("object_entity_id", sa.UUID(), nullable=False),
        sa.Column("relationship", _enum("identity_relationship"), nullable=False),
        sa.Column("computed_strength", _enum("resolution_strength"), nullable=False),
        sa.Column("effective_strength", _enum("resolution_strength"), nullable=False),
        sa.Column("resolution_method", sa.String(length=100), nullable=False),
        sa.Column("method_version", sa.String(length=50), nullable=False),
        sa.Column("assertion_hash", sa.String(length=64), nullable=False),
        sa.Column("status", _enum("assertion_status"), nullable=False),
        sa.Column("evidence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("override_applied", sa.Boolean(), nullable=False),
        sa.Column("override_reason", sa.Text(), nullable=True),
        sa.Column("override_actor", sa.String(length=255), nullable=True),
        sa.Column("effective_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["object_entity_id"],
            ["gis_core.analytical_entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_entity_id"],
            ["gis_core.analytical_entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gis_core",
    )
    op.create_index(
        "ix_identity_assertion_subject",
        "identity_assertion",
        ["subject_entity_id", "relationship"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "uq_identity_assertion_current",
        "identity_assertion",
        ["assertion_hash"],
        unique=True,
        schema="gis_core",
        postgresql_where=sa.text("effective_end IS NULL"),
    )
    op.create_table(
        "evidence_package",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("quality_run_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("analytical_entity_id", sa.UUID(), nullable=False),
        sa.Column("evidence_contract_id", sa.UUID(), nullable=False),
        sa.Column("demand_signal_id", sa.UUID(), nullable=True),
        sa.Column("market_definition_id", sa.UUID(), nullable=True),
        sa.Column("market_definition_version", sa.Integer(), nullable=True),
        sa.Column("condition_key", sa.String(length=100), nullable=False),
        sa.Column("classification", sa.String(length=100), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("sufficiency", _enum("demand_evidence_strength"), nullable=False),
        sa.Column("identity_resolution", _enum("resolution_strength"), nullable=False),
        sa.Column("source_independence", _enum("source_independence_state"), nullable=False),
        sa.Column("corroboration", _enum("corroboration_state"), nullable=False),
        sa.Column("rights_usability", _enum("rights_usability"), nullable=False),
        sa.Column("conflict_count", sa.Integer(), nullable=False),
        sa.Column("independent_source_count", sa.Integer(), nullable=False),
        sa.Column("limitations_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("method_version", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analytical_entity_id"],
            ["gis_core.analytical_entity.id"],
        ),
        sa.ForeignKeyConstraint(
            ["demand_signal_id"],
            ["gis_core.demand_signal.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_contract_id"],
            ["gis_core.evidence_contract.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_definition_id"],
            ["gis_core.market_definition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["quality_run_id"], ["gis_core.evidence_quality_run.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_hash", name="uq_evidence_package_identity"),
        schema="gis_core",
    )
    op.create_index(
        "ix_evidence_package_current",
        "evidence_package",
        ["tenant_id", "site_id", "condition_key", "period_end"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "evidence_gap",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_package_id", sa.UUID(), nullable=False),
        sa.Column("collection_target_id", sa.UUID(), nullable=True),
        sa.Column("gap_type", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("desired_evidence_capability", sa.String(length=100), nullable=True),
        sa.Column("urgency", _enum("collection_priority_tier"), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("planning_evidence_id", sa.UUID(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provenance_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_target_id"],
            ["gis_core.collection_target.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_package_id"], ["gis_core.evidence_package.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["planning_evidence_id"],
            ["gis_core.collection_target_evidence.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_hash", name="uq_evidence_gap_identity"),
        schema="gis_core",
    )
    op.create_index(
        "ix_evidence_gap_package",
        "evidence_gap",
        ["evidence_package_id", "gap_type", "resolved_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "evidence_package_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_package_id", sa.UUID(), nullable=False),
        sa.Column("evidence_key", sa.String(length=255), nullable=False),
        sa.Column("evidence_type", sa.String(length=100), nullable=False),
        sa.Column("evidence_reference_id", sa.UUID(), nullable=True),
        sa.Column("evidence_role", sa.String(length=100), nullable=False),
        sa.Column("root_source_key", sa.String(length=100), nullable=True),
        sa.Column("independence", _enum("source_independence_state"), nullable=False),
        sa.Column("method_compatibility", _enum("evidence_compatibility"), nullable=False),
        sa.Column("scope_compatibility", _enum("evidence_compatibility"), nullable=False),
        sa.Column("rights_usability", _enum("rights_usability"), nullable=False),
        sa.Column("supports_claim", sa.Boolean(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_package_id"], ["gis_core.evidence_package.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("evidence_package_id", "evidence_key", name="uq_evidence_package_item"),
        schema="gis_core",
    )
    op.create_index(
        "ix_evidence_package_root",
        "evidence_package_item",
        ["evidence_package_id", "root_source_key"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "evidence_quality_dimension",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evidence_package_id", sa.UUID(), nullable=False),
        sa.Column("dimension", _enum("quality_dimension_type"), nullable=False),
        sa.Column("state", _enum("quality_dimension_state"), nullable=False),
        sa.Column("method_key", sa.String(length=100), nullable=False),
        sa.Column("method_version", sa.String(length=50), nullable=False),
        sa.Column("observed_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("expected_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("reasons_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_package_id"], ["gis_core.evidence_package.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "evidence_package_id", "dimension", name="uq_evidence_package_dimension"
        ),
        schema="gis_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    for relation in (
        "mart_evidence_quality_current",
        "mart_evidence_quality_history",
        "mart_evidence_sufficiency",
        "mart_evidence_conflicts",
        "mart_evidence_corroboration",
        "mart_evidence_gaps",
        "mart_entity_resolution",
        "mart_source_independence",
        "mart_evidence_contract_status",
    ):
        op.execute(f"DROP TABLE IF EXISTS gis_analytics.{relation} CASCADE")
    for view in (
        "stg_analytical_entities",
        "stg_identity_assertions",
        "stg_evidence_contracts",
        "stg_evidence_quality_runs",
        "stg_evidence_packages",
        "stg_evidence_quality_dimensions",
        "stg_evidence_package_items",
        "stg_evidence_gaps",
    ):
        op.execute(f"DROP VIEW IF EXISTS gis_staging.{view} CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("evidence_quality_dimension", schema="gis_core")
    op.drop_index("ix_evidence_package_root", table_name="evidence_package_item", schema="gis_core")
    op.drop_table("evidence_package_item", schema="gis_core")
    op.drop_index("ix_evidence_gap_package", table_name="evidence_gap", schema="gis_core")
    op.drop_table("evidence_gap", schema="gis_core")
    op.drop_index("ix_evidence_package_current", table_name="evidence_package", schema="gis_core")
    op.drop_table("evidence_package", schema="gis_core")
    op.drop_index(
        "uq_identity_assertion_current",
        table_name="identity_assertion",
        schema="gis_core",
        postgresql_where=sa.text("effective_end IS NULL"),
    )
    op.drop_index(
        "ix_identity_assertion_subject", table_name="identity_assertion", schema="gis_core"
    )
    op.drop_table("identity_assertion", schema="gis_core")
    op.drop_index(
        "ix_evidence_quality_run_scope", table_name="evidence_quality_run", schema="gis_core"
    )
    op.drop_table("evidence_quality_run", schema="gis_core")
    op.drop_index("ix_analytical_entity_scope", table_name="analytical_entity", schema="gis_core")
    op.drop_table("analytical_entity", schema="gis_core")
    op.drop_table("evidence_contract", schema="gis_core")
    for name in (
        "quality_dimension_state",
        "quality_dimension_type",
        "evidence_compatibility",
        "rights_usability",
        "corroboration_state",
        "source_independence_state",
        "assertion_status",
        "resolution_strength",
        "identity_relationship",
        "analytical_entity_type",
    ):
        op.execute(f"DROP TYPE gis_core.{name}")
    # ### end Alembic commands ###
