"""activate production telemetry transport

Revision ID: 20260830_0008
Revises: 20260829_0007
Create Date: 2026-08-29 23:26:36.006847
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "20260830_0008"
down_revision: Union[str, None] = "20260829_0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "telemetry_transport_batch",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=False),
        sa.Column("transport", sa.String(length=32), nullable=False),
        sa.Column("transport_message_id", sa.String(length=255), nullable=False),
        sa.Column("batch_id", sa.UUID(), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("events_received", sa.Integer(), nullable=False),
        sa.Column("events_accepted", sa.Integer(), nullable=False),
        sa.Column("events_rejected", sa.Integer(), nullable=False),
        sa.Column("duplicates_ignored", sa.Integer(), nullable=False),
        sa.Column("payload_bytes", sa.Integer(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "events_received >= 0 AND events_accepted >= 0 AND events_rejected >= 0 AND duplicates_ignored >= 0 AND payload_bytes >= 0",
            name="ck_telemetry_batch_counters",
        ),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["gis_core.ingestion_run.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
            name="fk_telemetry_batch_site_tenant",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "transport", "transport_message_id", name="uq_telemetry_transport_message"
        ),
        schema="gis_core",
    )
    op.create_index(
        "ix_telemetry_batch_site_processed",
        "telemetry_transport_batch",
        ["site_id", "processed_at"],
        unique=False,
        schema="gis_core",
    )
    op.add_column(
        "event", sa.Column("ingestion_run_id", sa.UUID(), nullable=True), schema="gis_core"
    )
    op.create_foreign_key(
        "fk_event_ingestion_run",
        "event",
        "ingestion_run",
        ["ingestion_run_id"],
        ["id"],
        source_schema="gis_core",
        referent_schema="gis_core",
    )
    op.add_column("site", sa.Column("public_id", sa.UUID(), nullable=True), schema="gis_core")
    op.execute("UPDATE gis_core.site SET public_id = gen_random_uuid() WHERE public_id IS NULL")
    op.alter_column("site", "public_id", nullable=False, schema="gis_core")
    op.create_unique_constraint("uq_site_public_id", "site", ["public_id"], schema="gis_core")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_site_public_id", "site", schema="gis_core", type_="unique")
    op.drop_column("site", "public_id", schema="gis_core")
    op.drop_constraint("fk_event_ingestion_run", "event", schema="gis_core", type_="foreignkey")
    op.drop_column("event", "ingestion_run_id", schema="gis_core")
    op.drop_index(
        "ix_telemetry_batch_site_processed",
        table_name="telemetry_transport_batch",
        schema="gis_core",
    )
    op.drop_table("telemetry_transport_batch", schema="gis_core")
    # ### end Alembic commands ###
