"""add emerging demand intelligence

Revision ID: 20260831_0017
Revises: 20260830_0016
Create Date: 2026-08-30 22:09:31.302691
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260831_0017"
down_revision: Union[str, None] = "20260830_0016"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _enum(name: str) -> postgresql.ENUM:
    return postgresql.ENUM(name=name, schema="gis_core", create_type=False)


def upgrade() -> None:
    bind = op.get_bind()
    enums = {
        "demand_entity_type": ["QUERY", "TOPIC", "MARKET_SEGMENT", "MARKET"],
        "demand_signal_type": [
            "FIRST_OBSERVED",
            "EMERGING",
            "GROWING",
            "ACCELERATING",
            "DECELERATING",
            "DECLINING",
            "STABLE",
            "SPIKE",
            "REVERSAL",
            "INSUFFICIENT_HISTORY",
        ],
        "demand_evidence_strength": [
            "INSUFFICIENT",
            "LIMITED",
            "SUPPORTED",
            "STRONGLY_SUPPORTED",
        ],
        "demand_coverage_state": [
            "OBSERVED",
            "NO_DEMAND_OBSERVED",
            "NOT_OBSERVED",
            "NOT_COLLECTED",
            "INSUFFICIENT_HISTORY",
            "PARTIAL_COVERAGE",
            "COLLECTION_REGIME_CHANGED",
            "UNKNOWN",
        ],
        "demand_evidence_role": [
            "PRIMARY_DEMAND_EVIDENCE",
            "SUPPORTING_OWNED_SIGNAL",
            "SUPPORTING_COMPETITIVE_SIGNAL",
            "COLLECTION_COVERAGE_EVIDENCE",
        ],
        "validation_request_status": ["OPEN", "SATISFIED", "EXPIRED", "CANCELLED"],
    }
    for name, values in enums.items():
        postgresql.ENUM(*values, name=name, schema="gis_core").create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "demand_analysis_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("market_definition_id", sa.UUID(), nullable=False),
        sa.Column("market_definition_version", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.String(length=50), nullable=False),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("signal_count", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["market_definition_id"],
            ["gis_core.market_definition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "site_id", "fingerprint", name="uq_demand_analysis_run"),
        schema="gis_core",
    )
    op.create_index(
        "ix_demand_analysis_scope",
        "demand_analysis_run",
        ["tenant_id", "site_id", "analyzed_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "demand_signal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("analysis_run_id", sa.UUID(), nullable=False),
        sa.Column("market_definition_id", sa.UUID(), nullable=False),
        sa.Column("market_definition_version", sa.Integer(), nullable=False),
        sa.Column("collection_target_id", sa.UUID(), nullable=True),
        sa.Column("entity_type", _enum("demand_entity_type"), nullable=False),
        sa.Column("entity_key", sa.Text(), nullable=False),
        sa.Column("source_series_key", sa.String(length=64), nullable=False),
        sa.Column("signal_type", _enum("demand_signal_type"), nullable=False),
        sa.Column("window_key", sa.String(length=20), nullable=False),
        sa.Column("window_start", sa.Date(), nullable=False),
        sa.Column("window_end", sa.Date(), nullable=False),
        sa.Column("current_value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("prior_value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("absolute_change", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("relative_change", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("velocity", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("prior_velocity", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("acceleration", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("evidence_strength", _enum("demand_evidence_strength"), nullable=False),
        sa.Column("coverage_state", _enum("demand_coverage_state"), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column("collection_regime_changed", sa.Boolean(), nullable=False),
        sa.Column("policy_version", sa.String(length=50), nullable=False),
        sa.Column("reasons_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"], ["gis_core.demand_analysis_run.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["collection_target_id"],
            ["gis_core.collection_target.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_definition_id"],
            ["gis_core.market_definition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "analysis_run_id",
            "entity_type",
            "entity_key",
            "source_series_key",
            "signal_type",
            name="uq_demand_signal_run_entity",
        ),
        sa.UniqueConstraint("identity_hash"),
        schema="gis_core",
    )
    op.create_index(
        "ix_demand_signal_entity",
        "demand_signal",
        ["collection_target_id", "window_end"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_demand_signal_market",
        "demand_signal",
        ["market_definition_id", "signal_type", "window_end"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "demand_observation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("market_definition_id", sa.UUID(), nullable=False),
        sa.Column("market_definition_version", sa.Integer(), nullable=False),
        sa.Column("collection_target_id", sa.UUID(), nullable=True),
        sa.Column("entity_type", _enum("demand_entity_type"), nullable=False),
        sa.Column("entity_key", sa.Text(), nullable=False),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("source_connection_id", sa.UUID(), nullable=True),
        sa.Column("source_record_id", sa.String(length=255), nullable=True),
        sa.Column("source_metric", sa.String(length=150), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=8), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("resolution_days", sa.Integer(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("device", sa.String(length=32), nullable=True),
        sa.Column("semantic_class", _enum("event_semantic_class"), nullable=False),
        sa.Column("coverage_state", _enum("demand_coverage_state"), nullable=False),
        sa.Column("method_key", sa.String(length=100), nullable=False),
        sa.Column("method_version", sa.String(length=50), nullable=False),
        sa.Column("rights_policy_id", sa.UUID(), nullable=False),
        sa.Column("observation_key", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("provenance_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_end IS NULL OR effective_end >= effective_start",
            name="ck_demand_observation_window",
        ),
        sa.CheckConstraint("value IS NULL OR value >= 0", name="ck_demand_observation_value"),
        sa.ForeignKeyConstraint(
            ["collection_target_id"],
            ["gis_core.collection_target.id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_definition_id"],
            ["gis_core.market_definition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rights_policy_id"],
            ["gis_core.data_rights_policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_connection_id"],
            ["gis_core.data_source_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gis_raw",
    )
    op.create_index(
        "ix_demand_observation_series",
        "demand_observation",
        ["tenant_id", "site_id", "market_definition_id", "entity_key", "observed_date"],
        unique=False,
        schema="gis_raw",
    )
    op.create_index(
        "uq_demand_observation_current",
        "demand_observation",
        ["observation_key"],
        unique=True,
        schema="gis_raw",
        postgresql_where=sa.text("effective_end IS NULL"),
    )
    op.create_table(
        "demand_signal_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("demand_observation_id", sa.UUID(), nullable=True),
        sa.Column("role", _enum("demand_evidence_role"), nullable=False),
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("evidence_key", sa.String(length=255), nullable=False),
        sa.Column("semantic_class", _enum("event_semantic_class"), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["demand_observation_id"],
            ["gis_raw.demand_observation.id"],
        ),
        sa.ForeignKeyConstraint(["signal_id"], ["gis_core.demand_signal.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("signal_id", "evidence_key", name="uq_demand_signal_evidence"),
        schema="gis_core",
    )
    op.create_table(
        "demand_validation_request",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("collection_target_id", sa.UUID(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("desired_evidence_capability", sa.String(length=100), nullable=False),
        sa.Column("urgency", _enum("collection_priority_tier"), nullable=False),
        sa.Column("status", _enum("validation_request_status"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("provenance_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collection_target_id"],
            ["gis_core.collection_target.id"],
        ),
        sa.ForeignKeyConstraint(["signal_id"], ["gis_core.demand_signal.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("identity_hash", name="uq_demand_validation_request"),
        schema="gis_core",
    )
    op.create_index(
        "ix_demand_validation_target",
        "demand_validation_request",
        ["collection_target_id", "status", "expires_at"],
        unique=False,
        schema="gis_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    for relation in (
        "mart_demand_query_daily",
        "mart_demand_query_trend",
        "mart_demand_topic_daily",
        "mart_demand_segment_daily",
        "mart_demand_market_daily",
        "mart_emerging_demand",
        "mart_demand_acceleration",
        "mart_demand_spikes",
        "mart_demand_decline",
        "mart_demand_evidence_coverage",
    ):
        op.execute(f"DROP TABLE IF EXISTS gis_analytics.{relation} CASCADE")
    for view in (
        "stg_demand_observations",
        "stg_demand_analysis_runs",
        "stg_demand_signals",
        "stg_demand_signal_evidence",
        "stg_demand_validation_requests",
    ):
        op.execute(f"DROP VIEW IF EXISTS gis_staging.{view} CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_demand_validation_target", table_name="demand_validation_request", schema="gis_core"
    )
    op.drop_table("demand_validation_request", schema="gis_core")
    op.drop_table("demand_signal_evidence", schema="gis_core")
    op.drop_index(
        "uq_demand_observation_current",
        table_name="demand_observation",
        schema="gis_raw",
        postgresql_where=sa.text("effective_end IS NULL"),
    )
    op.drop_index("ix_demand_observation_series", table_name="demand_observation", schema="gis_raw")
    op.drop_table("demand_observation", schema="gis_raw")
    op.drop_index("ix_demand_signal_market", table_name="demand_signal", schema="gis_core")
    op.drop_index("ix_demand_signal_entity", table_name="demand_signal", schema="gis_core")
    op.drop_table("demand_signal", schema="gis_core")
    op.drop_index("ix_demand_analysis_scope", table_name="demand_analysis_run", schema="gis_core")
    op.drop_table("demand_analysis_run", schema="gis_core")
    for name in (
        "validation_request_status",
        "demand_evidence_role",
        "demand_coverage_state",
        "demand_evidence_strength",
        "demand_signal_type",
        "demand_entity_type",
    ):
        op.execute(f"DROP TYPE gis_core.{name}")
    # ### end Alembic commands ###
