"""add collection planning target management

Revision ID: 20260830_0016
Revises: 20260830_0015
Create Date: 2026-08-30 21:45:34.304126
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260830_0016"
down_revision: Union[str, None] = "20260830_0015"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _enum(name: str) -> postgresql.ENUM:
    return postgresql.ENUM(name=name, schema="gis_core", create_type=False)


def upgrade() -> None:
    bind = op.get_bind()
    enums = {
        "collection_target_type": ["QUERY", "DOMAIN", "URL", "TOPIC"],
        "collection_target_status": [
            "CANDIDATE",
            "ACTIVE",
            "DORMANT",
            "PAUSED",
            "REJECTED",
            "RETIRED",
        ],
        "collection_priority_tier": ["CRITICAL", "HIGH", "MEDIUM", "LOW", "DISCOVERY", "DORMANT"],
        "collection_cadence": [
            "DAILY",
            "MULTIPLE_PER_WEEK",
            "WEEKLY",
            "MONTHLY",
            "ON_DEMAND",
            "NONE",
        ],
        "collection_blocker": [
            "NONE",
            "BLOCKED_BY_RIGHTS",
            "BUDGET_BLOCKED",
            "NO_PROVIDER",
            "INSUFFICIENT_EVIDENCE",
            "UNKNOWN_COST",
            "OPERATOR_PAUSED",
        ],
        "collection_override_type": [
            "FORCE_ACTIVE",
            "FORCE_PAUSED",
            "FORCE_RETIRED",
            "FORCE_PRIORITY",
            "FORCE_CADENCE",
            "FORCE_COLLECTOR",
        ],
        "budget_decision": ["ALLOW", "BLOCK"],
    }
    for name, values in enums.items():
        postgresql.ENUM(*values, name=name, schema="gis_core").create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection_planning_policy",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("policy_key", sa.String(length=100), nullable=False),
        sa.Column("policy_version", sa.String(length=50), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("weights_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("thresholds_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cadence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["gis_core.tenant.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "policy_key", "policy_version", name="uq_collection_policy_version"
        ),
        schema="gis_core",
    )
    op.create_table(
        "collection_planning_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("market_definition_id", sa.UUID(), nullable=False),
        sa.Column("market_definition_version", sa.Integer(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.String(length=50), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("target_count", sa.Integer(), nullable=False),
        sa.Column("proposed_monthly_cost", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["market_definition_id"],
            ["gis_core.market_definition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["gis_core.collection_planning_policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "site_id", "fingerprint", name="uq_collection_planning_run"
        ),
        schema="gis_core",
    )
    op.create_index(
        "ix_collection_planning_run_scope",
        "collection_planning_run",
        ["tenant_id", "site_id", "evaluated_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "collection_target",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("market_definition_id", sa.UUID(), nullable=False),
        sa.Column("market_definition_version", sa.Integer(), nullable=False),
        sa.Column("target_type", _enum("collection_target_type"), nullable=False),
        sa.Column("normalized_identity", sa.Text(), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("display_value", sa.Text(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=True),
        sa.Column("device", sa.String(length=32), nullable=True),
        sa.Column("status", _enum("collection_target_status"), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dormant_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("human_managed", sa.Boolean(), nullable=False),
        sa.Column("current_policy_version", sa.String(length=100), nullable=True),
        sa.Column("provenance_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["market_definition_id"],
            ["gis_core.market_definition.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "site_id", "identity_hash", name="uq_collection_target"),
        schema="gis_core",
    )
    op.create_index(
        "ix_collection_target_market",
        "collection_target",
        ["market_definition_id", "market_definition_version"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_collection_target_status",
        "collection_target",
        ["tenant_id", "site_id", "status"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "collector_capability",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("capability_key", sa.String(length=100), nullable=False),
        sa.Column("pipeline_id", sa.UUID(), nullable=False),
        sa.Column("target_type", _enum("collection_target_type"), nullable=False),
        sa.Column("evidence_product", sa.String(length=100), nullable=False),
        sa.Column("estimated_cost_per_run", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("preference", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("configuration_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_id"],
            ["gis_core.pipeline_definition.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("capability_key", "target_type", name="uq_collector_capability_target"),
        schema="gis_core",
    )
    op.create_table(
        "collection_planning_decision",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("planning_run_id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("policy_version", sa.String(length=50), nullable=False),
        sa.Column("priority_score", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("priority_tier", _enum("collection_priority_tier"), nullable=False),
        sa.Column("component_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unknown_components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("computed_status", _enum("collection_target_status"), nullable=False),
        sa.Column("effective_status", _enum("collection_target_status"), nullable=False),
        sa.Column("computed_cadence", _enum("collection_cadence"), nullable=False),
        sa.Column("effective_cadence", _enum("collection_cadence"), nullable=False),
        sa.Column("primary_blocker", _enum("collection_blocker"), nullable=False),
        sa.Column("blockers_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("override_applied", sa.Boolean(), nullable=False),
        sa.Column("explanation_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("priority_score BETWEEN 0 AND 1", name="ck_collection_priority_score"),
        sa.ForeignKeyConstraint(
            ["planning_run_id"], ["gis_core.collection_planning_run.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["gis_core.collection_target.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("planning_run_id", "target_id", name="uq_collection_decision_target"),
        schema="gis_core",
    )
    op.create_index(
        "ix_collection_decision_target",
        "collection_planning_decision",
        ["target_id", "evaluated_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "collection_target_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("source_system", sa.String(length=100), nullable=False),
        sa.Column("evidence_type", sa.String(length=100), nullable=False),
        sa.Column("evidence_identifier", sa.String(length=255), nullable=False),
        sa.Column("evidence_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("semantic_class", _enum("event_semantic_class"), nullable=False),
        sa.Column("signal_name", sa.String(length=100), nullable=False),
        sa.Column("signal_value", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_id"], ["gis_core.collection_target.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "target_id",
            "source_system",
            "evidence_type",
            "evidence_identifier",
            name="uq_collection_target_evidence",
        ),
        schema="gis_core",
    )
    op.create_index(
        "ix_collection_evidence_target",
        "collection_target_evidence",
        ["target_id", "evidence_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "collection_target_override",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("override_type", _enum("collection_override_type"), nullable=False),
        sa.Column("forced_priority", _enum("collection_priority_tier"), nullable=True),
        sa.Column("forced_cadence", _enum("collection_cadence"), nullable=True),
        sa.Column("forced_capability_id", sa.UUID(), nullable=True),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleared_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["forced_capability_id"],
            ["gis_core.collector_capability.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"], ["gis_core.collection_target.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gis_core",
    )
    op.create_index(
        "uq_collection_override_active",
        "collection_target_override",
        ["target_id"],
        unique=True,
        schema="gis_core",
        postgresql_where=sa.text("active"),
    )
    op.create_table(
        "collection_plan_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("collector_capability_id", sa.UUID(), nullable=False),
        sa.Column("data_source_connection_id", sa.UUID(), nullable=True),
        sa.Column("desired_cadence", _enum("collection_cadence"), nullable=False),
        sa.Column("effective_cadence", _enum("collection_cadence"), nullable=False),
        sa.Column("rights_status", _enum("rights_status"), nullable=False),
        sa.Column("budget_decision", _enum("budget_decision"), nullable=False),
        sa.Column("estimated_cost_per_run", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("estimated_runs_month", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("estimated_monthly_cost", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("blocker", _enum("collection_blocker"), nullable=False),
        sa.Column("scheduled_target_id", sa.UUID(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("explanation_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "estimated_monthly_cost IS NULL OR estimated_monthly_cost >= 0",
            name="ck_collection_plan_cost",
        ),
        sa.CheckConstraint("estimated_runs_month >= 0", name="ck_collection_plan_runs"),
        sa.ForeignKeyConstraint(
            ["collector_capability_id"],
            ["gis_core.collector_capability.id"],
        ),
        sa.ForeignKeyConstraint(
            ["data_source_connection_id"],
            ["gis_core.data_source_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id"], ["gis_core.collection_planning_decision.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_target_id"],
            ["gis_core.scheduled_target.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "decision_id", "collector_capability_id", name="uq_collection_plan_item"
        ),
        schema="gis_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    for relation in (
        "mart_collection_target_current",
        "mart_collection_target_history",
        "mart_collection_plan_current",
        "mart_collection_priority_distribution",
        "mart_collection_cost_forecast",
        "mart_collection_blockers",
        "mart_collection_market_coverage",
        "mart_collection_provider_mix",
    ):
        op.execute(f"DROP TABLE IF EXISTS gis_analytics.{relation} CASCADE")
    for view in (
        "stg_collection_targets",
        "stg_collection_target_evidence",
        "stg_collection_planning_runs",
        "stg_collection_planning_decisions",
        "stg_collection_plan_items",
        "stg_collector_capabilities",
        "stg_collection_target_overrides",
    ):
        op.execute(f"DROP VIEW IF EXISTS gis_staging.{view} CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_plan_item", schema="gis_core")
    op.drop_index(
        "uq_collection_override_active",
        table_name="collection_target_override",
        schema="gis_core",
        postgresql_where=sa.text("active"),
    )
    op.drop_table("collection_target_override", schema="gis_core")
    op.drop_index(
        "ix_collection_evidence_target", table_name="collection_target_evidence", schema="gis_core"
    )
    op.drop_table("collection_target_evidence", schema="gis_core")
    op.drop_index(
        "ix_collection_decision_target",
        table_name="collection_planning_decision",
        schema="gis_core",
    )
    op.drop_table("collection_planning_decision", schema="gis_core")
    op.drop_table("collector_capability", schema="gis_core")
    op.drop_index("ix_collection_target_status", table_name="collection_target", schema="gis_core")
    op.drop_index("ix_collection_target_market", table_name="collection_target", schema="gis_core")
    op.drop_table("collection_target", schema="gis_core")
    op.drop_index(
        "ix_collection_planning_run_scope", table_name="collection_planning_run", schema="gis_core"
    )
    op.drop_table("collection_planning_run", schema="gis_core")
    op.drop_table("collection_planning_policy", schema="gis_core")
    for name in (
        "budget_decision",
        "collection_override_type",
        "collection_blocker",
        "collection_cadence",
        "collection_priority_tier",
        "collection_target_status",
        "collection_target_type",
    ):
        op.execute(f"DROP TYPE gis_core.{name}")
    # ### end Alembic commands ###
