"""Add first-party telemetry

Revision ID: 20260829_0004
Revises: 20260829_0003
Create Date: 2026-08-29 13:33:00.612725
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260829_0004"
down_revision: Union[str, None] = "20260829_0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_connection_tenant_site_id",
        "data_source_connection",
        ["tenant_id", "site_id", "id"],
        schema="gis_core",
    )
    op.create_table(
        "session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("data_source_connection_id", sa.UUID(), nullable=False),
        sa.Column("rights_policy_id", sa.UUID(), nullable=False),
        sa.Column("session_key", sa.UUID(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("landing_url", sa.String(length=2048), nullable=True),
        sa.Column("landing_path", sa.String(length=2048), nullable=True),
        sa.Column("referrer_url", sa.String(length=2048), nullable=True),
        sa.Column("initial_utm_source", sa.String(length=255), nullable=True),
        sa.Column("initial_utm_medium", sa.String(length=255), nullable=True),
        sa.Column("initial_utm_campaign", sa.String(length=255), nullable=True),
        sa.Column("initial_utm_term", sa.String(length=255), nullable=True),
        sa.Column("initial_utm_content", sa.String(length=255), nullable=True),
        sa.Column("initial_gclid", sa.String(length=512), nullable=True),
        sa.Column("initial_msclkid", sa.String(length=512), nullable=True),
        sa.Column("initial_referrer_domain", sa.String(length=253), nullable=True),
        sa.Column("device_category", sa.String(length=64), nullable=True),
        sa.Column("browser_family", sa.String(length=128), nullable=True),
        sa.Column("os_family", sa.String(length=128), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("region_code", sa.String(length=16), nullable=True),
        sa.Column("anonymous_visitor_key", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at", name="ck_session_end_time"
        ),
        sa.ForeignKeyConstraint(
            ["rights_policy_id"],
            ["gis_core.data_rights_policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "data_source_connection_id"],
            [
                "gis_core.data_source_connection.tenant_id",
                "gis_core.data_source_connection.site_id",
                "gis_core.data_source_connection.id",
            ],
            name="fk_session_connection_scope",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
            name="fk_session_site_tenant",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "site_id", "id", name="uq_session_scope_id"),
        sa.UniqueConstraint("tenant_id", "site_id", "session_key", name="uq_session_scope_key"),
        schema="gis_core",
    )
    op.create_index(
        "ix_session_anonymous_visitor",
        "session",
        ["anonymous_visitor_key"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_session_landing_path", "session", ["landing_path"], unique=False, schema="gis_core"
    )
    op.create_index(
        "ix_session_tenant_site_started",
        "session",
        ["tenant_id", "site_id", "started_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "calculator_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("data_source_connection_id", sa.UUID(), nullable=False),
        sa.Column("rights_policy_id", sa.UUID(), nullable=False),
        sa.Column("calculator_run_key", sa.UUID(), nullable=False),
        sa.Column("calculator_type", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("initial_page_path", sa.String(length=2048), nullable=True),
        sa.Column("input_schema_version", sa.String(length=100), nullable=False),
        sa.Column("result_schema_version", sa.String(length=100), nullable=True),
        sa.Column("input_bucket_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result_bucket_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("recalculation_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= started_at", name="ck_calculator_run_times"
        ),
        sa.CheckConstraint(
            "recalculation_count >= 0", name="ck_calculator_run_recalculation_count"
        ),
        sa.ForeignKeyConstraint(
            ["rights_policy_id"],
            ["gis_core.data_rights_policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "data_source_connection_id"],
            [
                "gis_core.data_source_connection.tenant_id",
                "gis_core.data_source_connection.site_id",
                "gis_core.data_source_connection.id",
            ],
            name="fk_calculator_run_connection_scope",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "session_id"],
            ["gis_core.session.tenant_id", "gis_core.session.site_id", "gis_core.session.id"],
            name="fk_calculator_run_session_scope",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
            name="fk_calculator_run_site_tenant",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "site_id", "calculator_run_key", name="uq_calculator_run_scope_key"
        ),
        sa.UniqueConstraint("tenant_id", "site_id", "id", name="uq_calculator_run_scope_id"),
        schema="gis_core",
    )
    op.create_index(
        "ix_calculator_run_session",
        "calculator_run",
        ["session_id"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_calculator_run_tenant_site_started",
        "calculator_run",
        ["tenant_id", "site_id", "started_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_calculator_run_type",
        "calculator_run",
        ["calculator_type"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("calculator_run_id", sa.UUID(), nullable=True),
        sa.Column("data_source_connection_id", sa.UUID(), nullable=False),
        sa.Column("rights_policy_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("event_name", sa.String(length=100), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("page_url", sa.String(length=2048), nullable=True),
        sa.Column("page_path", sa.String(length=2048), nullable=True),
        sa.Column("event_properties", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("event_version > 0", name="ck_event_version_positive"),
        sa.ForeignKeyConstraint(
            ["rights_policy_id"],
            ["gis_core.data_rights_policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "data_source_connection_id"],
            [
                "gis_core.data_source_connection.tenant_id",
                "gis_core.data_source_connection.site_id",
                "gis_core.data_source_connection.id",
            ],
            name="fk_event_connection_scope",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "calculator_run_id"],
            [
                "gis_core.calculator_run.tenant_id",
                "gis_core.calculator_run.site_id",
                "gis_core.calculator_run.id",
            ],
            name="fk_event_calculator_run_scope",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "session_id"],
            ["gis_core.session.tenant_id", "gis_core.session.site_id", "gis_core.session.id"],
            name="fk_event_session_scope",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
            name="fk_event_site_tenant",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "site_id", "event_id", name="uq_event_scope_id"),
        sa.UniqueConstraint("tenant_id", "site_id", "id", name="uq_event_internal_scope_id"),
        schema="gis_core",
    )
    op.create_index(
        "ix_event_calculator_run", "event", ["calculator_run_id"], unique=False, schema="gis_core"
    )
    op.create_index(
        "ix_event_name_occurred",
        "event",
        ["event_name", "occurred_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_index("ix_event_page_path", "event", ["page_path"], unique=False, schema="gis_core")
    op.create_index(
        "ix_event_session_occurred",
        "event",
        ["session_id", "occurred_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_event_tenant_site_occurred",
        "event",
        ["tenant_id", "site_id", "occurred_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "conversion",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("calculator_run_id", sa.UUID(), nullable=True),
        sa.Column("data_source_connection_id", sa.UUID(), nullable=False),
        sa.Column("rights_policy_id", sa.UUID(), nullable=False),
        sa.Column("conversion_id", sa.UUID(), nullable=False),
        sa.Column("conversion_type", sa.String(length=100), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_event_id", sa.UUID(), nullable=True),
        sa.Column("conversion_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["rights_policy_id"],
            ["gis_core.data_rights_policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "data_source_connection_id"],
            [
                "gis_core.data_source_connection.tenant_id",
                "gis_core.data_source_connection.site_id",
                "gis_core.data_source_connection.id",
            ],
            name="fk_conversion_connection_scope",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "calculator_run_id"],
            [
                "gis_core.calculator_run.tenant_id",
                "gis_core.calculator_run.site_id",
                "gis_core.calculator_run.id",
            ],
            name="fk_conversion_calculator_run_scope",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "session_id"],
            ["gis_core.session.tenant_id", "gis_core.session.site_id", "gis_core.session.id"],
            name="fk_conversion_session_scope",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "source_event_id"],
            ["gis_core.event.tenant_id", "gis_core.event.site_id", "gis_core.event.id"],
            name="fk_conversion_source_event_scope",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
            name="fk_conversion_site_tenant",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "site_id", "conversion_id", name="uq_conversion_scope_id"),
        schema="gis_core",
    )
    op.create_index(
        "ix_conversion_calculator_run",
        "conversion",
        ["calculator_run_id"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_conversion_session", "conversion", ["session_id"], unique=False, schema="gis_core"
    )
    op.create_index(
        "ix_conversion_tenant_site_occurred",
        "conversion",
        ["tenant_id", "site_id", "occurred_at"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_conversion_type_occurred",
        "conversion",
        ["conversion_type", "occurred_at"],
        unique=False,
        schema="gis_core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_conversion_type_occurred", table_name="conversion", schema="gis_core")
    op.drop_index("ix_conversion_tenant_site_occurred", table_name="conversion", schema="gis_core")
    op.drop_index("ix_conversion_session", table_name="conversion", schema="gis_core")
    op.drop_index("ix_conversion_calculator_run", table_name="conversion", schema="gis_core")
    op.drop_table("conversion", schema="gis_core")
    op.drop_index("ix_event_tenant_site_occurred", table_name="event", schema="gis_core")
    op.drop_index("ix_event_session_occurred", table_name="event", schema="gis_core")
    op.drop_index("ix_event_page_path", table_name="event", schema="gis_core")
    op.drop_index("ix_event_name_occurred", table_name="event", schema="gis_core")
    op.drop_index("ix_event_calculator_run", table_name="event", schema="gis_core")
    op.drop_table("event", schema="gis_core")
    op.drop_index("ix_calculator_run_type", table_name="calculator_run", schema="gis_core")
    op.drop_index(
        "ix_calculator_run_tenant_site_started", table_name="calculator_run", schema="gis_core"
    )
    op.drop_index("ix_calculator_run_session", table_name="calculator_run", schema="gis_core")
    op.drop_table("calculator_run", schema="gis_core")
    op.drop_index("ix_session_tenant_site_started", table_name="session", schema="gis_core")
    op.drop_index("ix_session_landing_path", table_name="session", schema="gis_core")
    op.drop_index("ix_session_anonymous_visitor", table_name="session", schema="gis_core")
    op.drop_table("session", schema="gis_core")
    op.execute(
        "ALTER TABLE gis_core.data_source_connection "
        "DROP CONSTRAINT IF EXISTS uq_connection_tenant_site_id"
    )
    # ### end Alembic commands ###
