"""add serp and experience intelligence

Revision ID: 20260829_0007
Revises: 20260829_0006
Create Date: 2026-08-29 21:16:26.455901
"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260829_0007"
down_revision: Union[str, None] = "20260829_0006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracked_query",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("normalized_query", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("cadence", sa.String(length=32), nullable=False),
        sa.Column("device", sa.String(length=32), nullable=False),
        sa.Column("search_engine", sa.String(length=32), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("location_code", sa.Integer(), nullable=True),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=False),
        sa.Column("requested_depth", sa.Integer(), nullable=False),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "requested_depth > 0 AND requested_depth <= 1000", name="ck_tracked_query_depth"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "site_id",
            "normalized_query",
            "search_engine",
            "country_code",
            "location_code",
            "language_code",
            "device",
            name="uq_tracked_query_context",
        ),
        schema="gis_core",
    )
    op.create_index(
        "ix_tracked_query_normalized",
        "tracked_query",
        ["normalized_query"],
        unique=False,
        schema="gis_core",
    )
    op.create_index(
        "ix_tracked_query_tenant_site_active",
        "tracked_query",
        ["tenant_id", "site_id", "active"],
        unique=False,
        schema="gis_core",
    )
    op.create_table(
        "experience_observation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=False),
        sa.Column("data_source_connection_id", sa.UUID(), nullable=False),
        sa.Column("rights_policy_id", sa.UUID(), nullable=False),
        sa.Column("rights_policy_version", sa.String(length=100), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("target", sa.Text(), nullable=False),
        sa.Column("normalized_target", sa.Text(), nullable=False),
        sa.Column(
            "measurement_type",
            sa.Enum("FIELD", "LAB", name="experience_measurement_type", schema="gis_core"),
            nullable=False,
        ),
        sa.Column(
            "scope",
            sa.Enum("URL", "ORIGIN", name="experience_scope", schema="gis_core"),
            nullable=False,
        ),
        sa.Column(
            "form_factor",
            sa.Enum(
                "MOBILE",
                "DESKTOP",
                "TABLET",
                "ALL",
                "UNKNOWN",
                name="experience_form_factor",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "availability",
            sa.Enum(
                "DATA_AVAILABLE",
                "INSUFFICIENT_DATA",
                "FAILED",
                name="experience_availability",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column(
            "metric",
            sa.Enum(
                "LCP",
                "INP",
                "CLS",
                "FCP",
                "TTFB",
                "PERFORMANCE_SCORE",
                "ACCESSIBILITY_SCORE",
                "BEST_PRACTICES_SCORE",
                "SEO_SCORE",
                name="experience_metric",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column("metric_value", sa.Numeric(precision=20, scale=6), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("percentile", sa.Integer(), nullable=True),
        sa.Column("classification", sa.String(length=32), nullable=True),
        sa.Column("good_proportion", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("needs_improvement_proportion", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("poor_proportion", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("provider_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "good_proportion IS NULL OR good_proportion BETWEEN 0 AND 1", name="ck_experience_good"
        ),
        sa.CheckConstraint("metric_value IS NULL OR metric_value >= 0", name="ck_experience_value"),
        sa.CheckConstraint(
            "needs_improvement_proportion IS NULL OR needs_improvement_proportion BETWEEN 0 AND 1",
            name="ck_experience_needs",
        ),
        sa.CheckConstraint(
            "poor_proportion IS NULL OR poor_proportion BETWEEN 0 AND 1", name="ck_experience_poor"
        ),
        sa.ForeignKeyConstraint(
            ["rights_policy_id"],
            ["gis_core.data_rights_policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "data_source_connection_id"],
            ["gis_core.data_source_connection.tenant_id", "gis_core.data_source_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "ingestion_run_id"],
            [
                "gis_core.ingestion_run.tenant_id",
                "gis_core.ingestion_run.site_id",
                "gis_core.ingestion_run.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gis_raw",
    )
    op.create_index(
        "ix_experience_ingestion_run",
        "experience_observation",
        ["ingestion_run_id"],
        unique=False,
        schema="gis_raw",
    )
    op.create_index(
        "ix_experience_target_period",
        "experience_observation",
        ["normalized_target", "period_end"],
        unique=False,
        schema="gis_raw",
    )
    op.create_table(
        "serp_observation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.UUID(), nullable=False),
        sa.Column("tracked_query_id", sa.UUID(), nullable=False),
        sa.Column("ingestion_run_id", sa.UUID(), nullable=False),
        sa.Column("data_source_connection_id", sa.UUID(), nullable=False),
        sa.Column("rights_policy_id", sa.UUID(), nullable=False),
        sa.Column("rights_policy_version", sa.String(length=100), nullable=False),
        sa.Column("provider_task_id", sa.String(length=255), nullable=True),
        sa.Column("observation_key", sa.String(length=64), nullable=False),
        sa.Column("observed_date", sa.Date(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("search_engine", sa.String(length=32), nullable=False),
        sa.Column("query_text", sa.Text(), nullable=False),
        sa.Column("normalized_query", sa.Text(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("location_code", sa.Integer(), nullable=True),
        sa.Column("location_name", sa.String(length=255), nullable=True),
        sa.Column("language_code", sa.String(length=16), nullable=False),
        sa.Column("device", sa.String(length=32), nullable=False),
        sa.Column("requested_depth", sa.Integer(), nullable=False),
        sa.Column("effective_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "effective_end IS NULL OR effective_end >= effective_start",
            name="ck_serp_effective_window",
        ),
        sa.ForeignKeyConstraint(
            ["rights_policy_id"],
            ["gis_core.data_rights_policy.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "data_source_connection_id"],
            ["gis_core.data_source_connection.tenant_id", "gis_core.data_source_connection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id", "ingestion_run_id"],
            [
                "gis_core.ingestion_run.tenant_id",
                "gis_core.ingestion_run.site_id",
                "gis_core.ingestion_run.id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "site_id"],
            ["gis_core.site.tenant_id", "gis_core.site.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tracked_query_id"],
            ["gis_core.tracked_query.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="gis_raw",
    )
    op.create_index(
        "ix_serp_ingestion_run",
        "serp_observation",
        ["ingestion_run_id"],
        unique=False,
        schema="gis_raw",
    )
    op.create_index(
        "ix_serp_query_date",
        "serp_observation",
        ["tracked_query_id", "observed_date"],
        unique=False,
        schema="gis_raw",
    )
    op.create_index(
        "uq_serp_current_observation",
        "serp_observation",
        ["observation_key"],
        unique=True,
        schema="gis_raw",
        postgresql_where=sa.text("effective_end IS NULL"),
    )
    op.create_table(
        "serp_result",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("serp_observation_id", sa.UUID(), nullable=False),
        sa.Column("rank_absolute", sa.Integer(), nullable=False),
        sa.Column("rank_group", sa.Integer(), nullable=True),
        sa.Column(
            "feature_type",
            sa.Enum(
                "ORGANIC",
                "PAID",
                "FEATURED_SNIPPET",
                "AI_ANSWER",
                "PEOPLE_ALSO_ASK",
                "LOCAL_PACK",
                "IMAGE",
                "VIDEO",
                "SHOPPING",
                "KNOWLEDGE_PANEL",
                "NEWS",
                "DISCUSSION_FORUM",
                "RELATED_SEARCH",
                "SITELINK",
                "MAP",
                "OTHER",
                "UNKNOWN",
                name="serp_feature_type",
                schema="gis_core",
            ),
            nullable=False,
        ),
        sa.Column("provider_type", sa.String(length=100), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("normalized_url", sa.Text(), nullable=True),
        sa.Column("hostname", sa.String(length=253), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("snippet", sa.Text(), nullable=True),
        sa.Column("breadcrumb", sa.Text(), nullable=True),
        sa.Column("is_paid", sa.Boolean(), nullable=False),
        sa.Column("is_organic", sa.Boolean(), nullable=False),
        sa.Column("is_feature", sa.Boolean(), nullable=False),
        sa.Column(
            "ownership",
            sa.Enum(
                "OWN_SITE", "KNOWN_COMPETITOR", "OTHER", name="result_ownership", schema="gis_core"
            ),
            nullable=False,
        ),
        sa.Column("provider_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("rank_absolute > 0", name="ck_serp_result_rank"),
        sa.ForeignKeyConstraint(
            ["serp_observation_id"], ["gis_raw.serp_observation.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "serp_observation_id",
            "rank_absolute",
            "provider_type",
            name="uq_serp_result_position_type",
        ),
        schema="gis_raw",
    )
    op.create_index(
        "ix_serp_result_domain", "serp_result", ["hostname"], unique=False, schema="gis_raw"
    )
    op.create_index(
        "ix_serp_result_observation",
        "serp_result",
        ["serp_observation_id"],
        unique=False,
        schema="gis_raw",
    )
    op.create_index(
        "ix_serp_result_url", "serp_result", ["normalized_url"], unique=False, schema="gis_raw"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_serp_result_url", table_name="serp_result", schema="gis_raw")
    op.drop_index("ix_serp_result_observation", table_name="serp_result", schema="gis_raw")
    op.drop_index("ix_serp_result_domain", table_name="serp_result", schema="gis_raw")
    op.drop_table("serp_result", schema="gis_raw")
    op.drop_index(
        "uq_serp_current_observation",
        table_name="serp_observation",
        schema="gis_raw",
        postgresql_where=sa.text("effective_end IS NULL"),
    )
    op.drop_index("ix_serp_query_date", table_name="serp_observation", schema="gis_raw")
    op.drop_index("ix_serp_ingestion_run", table_name="serp_observation", schema="gis_raw")
    op.drop_table("serp_observation", schema="gis_raw")
    op.drop_index(
        "ix_experience_target_period", table_name="experience_observation", schema="gis_raw"
    )
    op.drop_index(
        "ix_experience_ingestion_run", table_name="experience_observation", schema="gis_raw"
    )
    op.drop_table("experience_observation", schema="gis_raw")
    op.drop_index(
        "ix_tracked_query_tenant_site_active", table_name="tracked_query", schema="gis_core"
    )
    op.drop_index("ix_tracked_query_normalized", table_name="tracked_query", schema="gis_core")
    op.drop_table("tracked_query", schema="gis_core")
    sa.Enum(name="result_ownership", schema="gis_core").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="serp_feature_type", schema="gis_core").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="experience_metric", schema="gis_core").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="experience_availability", schema="gis_core").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="experience_form_factor", schema="gis_core").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="experience_scope", schema="gis_core").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="experience_measurement_type", schema="gis_core").drop(
        op.get_bind(), checkfirst=True
    )
    # ### end Alembic commands ###
