"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {api,siteScope} from "@/lib/api";
import {humanize} from "@/lib/format";
import {ErrorState,LoadingState,PageHeader,StatusBadge} from "./ui";
type Cited={text:string;nature:string;supporting_reference_ids:string[]};
type Proposal={id:string;status:string;category:string;target_region:string;current_observed_state:string;proposed_instruction:string;expected_qualitative_effect:string;risk:string;supporting_reference_ids:string[]};
type Brief={status:string;summary:string;exact_query:string;candidate_url:string;market_id:string;user_need:string;recommended_page_role:string;recommendations:Record<string,Cited[]>;prohibited_claims:string[];assumptions:string[];conflicts:string[];limitations:string[];remaining_gaps:string[];next_action:string;review_dependencies:Array<{review:string;required:boolean}>;proposals:Proposal[];technical:Record<string,unknown>};
export function ContentBriefDetail({investigationId,briefId}:{investigationId:string;briefId:string}) {
  const [data,setData]=useState<Brief>();const [error,setError]=useState<string>();
  useEffect(()=>{api<Brief>(`/api/v1/seo-investigations/${investigationId}/briefs/${briefId}?${siteScope()}`).then(setData).catch((e:Error)=>setError(e.message))},[investigationId,briefId]);
  if(error)return <ErrorState message={error}/>;if(!data)return <LoadingState/>;
  const section=(key:string,title:string)=><section className="semanticSection"><h2>{title}</h2>{(data.recommendations[key]??[]).map((item,index)=><article className="recordCard" key={`${key}-${index}`}><strong>Draft editorial suggestion</strong><p>{item.text}</p><small>{humanize(item.nature)} · {item.supporting_reference_ids.length} governed references</small></article>)}</section>;
  return <><nav className="breadcrumbs"><Link href={`/seo-investigations/${investigationId}/briefs`}>Content briefs</Link><span>→</span><strong>Brief</strong></nav><PageHeader eyebrow="Draft—not published content" title="Evidence-backed content brief" description={data.summary}/><StatusBadge>{humanize(data.status)}</StatusBadge><section className="semanticSection"><h2>Recommendation summary</h2><p>{data.recommended_page_role}</p><p><strong>User need:</strong> {data.user_need}</p></section><section className="semanticSection"><h2>Exact governed scope</h2><p>{data.exact_query}</p><p>{data.candidate_url}</p><p>Market: {data.market_id}</p></section><section className="semanticSection"><h2>Readiness and review</h2><p>{data.next_action}</p><ul>{data.review_dependencies.map(item=><li key={item.review}>{humanize(item.review)}: {item.required?"required":"optional"}</li>)}</ul></section>{section("suggested_sections","What should change and suggested page structure")}{section("unchanged","What should remain unchanged")}{section("title_meta","Proposed title and metadata")}{section("headings","Proposed headings")}{section("internal_links","Internal-link recommendations")}{section("accessibility_usability","Usability and accessibility")}{section("structured_data","Structured-data recommendations")}{section("measurement","Measurement requirements")}<section className="semanticSection"><h2>Bounded page-change proposals</h2>{data.proposals.map(proposal=><article className="recordCard" key={proposal.id}><h3>{humanize(proposal.category)} — {proposal.target_region}</h3><StatusBadge>{humanize(proposal.status)}</StatusBadge><p><strong>Observed state:</strong> {proposal.current_observed_state}</p><p><strong>Draft instruction:</strong> {proposal.proposed_instruction}</p><p>{proposal.expected_qualitative_effect}</p><p><strong>Risk:</strong> {proposal.risk}</p><p>{proposal.supporting_reference_ids.length} governed supporting references. Approval does not implement this proposal.</p></article>)}</section><section className="semanticSection"><h2>Risks, conflicts, assumptions, and limitations</h2><ul>{[...data.conflicts,...data.assumptions,...data.limitations,...data.remaining_gaps].map((item,index)=><li key={`${index}-${item}`}>{item}</li>)}</ul></section><section className="semanticSection"><h2>Supporting evidence and non-claims</h2><p>Every material suggestion is mapped to governed references in technical lineage.</p><ul>{data.prohibited_claims.map(item=><li key={item}>Must not claim: {item}</li>)}</ul></section><section className="semanticSection"><h2>Human reviews</h2><p>Reviews are append-only. No approval publishes or edits the page.</p></section><section className="semanticSection"><h2>Version history</h2><p>Compare immutable versions from the brief list. A newer version does not imply implementation.</p></section><details><summary>Technical lineage</summary><pre>{JSON.stringify(data.technical,null,2)}</pre></details></>;
}
