"use client";

import {useCallback, useEffect, useState} from "react";
import {api, siteScope} from "@/lib/api";
import type {Resource} from "@/lib/types";
import {ErrorState, LoadingState, PageHeader, StatusBadge} from "./ui";

export function RecommendationReview({id}: {id: string}) {
  const [data, setData] = useState<Resource>(); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false); const [message, setMessage] = useState<string>();
  const load = useCallback(() => api<Resource>(`/api/v1/recommendations/${id}?${siteScope()}`).then(setData).catch((value: Error) => setError(value.message)), [id]);
  useEffect(() => { void load(); }, [load]);
  async function decide(decision: "accept" | "reject", candidateId?: string) { setPending(true); setError(undefined); try { const result = await api<{intervention_approved: boolean}>(`/api/v1/recommendations/${id}/${decision}?${siteScope()}`, {method: "POST", body: JSON.stringify({actor: "local-operator", reason: decision === "reject" ? "OPERATOR_REJECTED" : undefined, candidate_ids: candidateId ? [candidateId] : []})}); setMessage(result.intervention_approved ? "Unexpected approval state" : decision === "accept" ? "Candidate accepted. A DRAFT intervention was created; it is not approved." : "Recommendation rejected and audit history preserved."); await load(); } catch (value) { setError((value as Error).message); } finally { setPending(false); } }
  if (error) return <ErrorState message={error}/>; if (!data) return <LoadingState/>;
  const candidates = (data.data.candidates ?? []) as Record<string, unknown>[];
  return <><PageHeader eyebrow="Recommendation review" title={String(data.data.summary ?? "Recommendation")} description="Review evidence fit, assumptions, limitations, feasibility and measurement before deciding."/><div className="notice"><strong>Fixture / development recommendation provider</strong><p>Accepting a candidate creates an intervention draft. It does not approve, schedule, or execute it.</p></div>{message && <div className="state" role="status">{message}</div>}<section className="candidateGrid">{candidates.map((candidate) => <article className="candidate" key={String(candidate.id)}><div><StatusBadge domain="priority">Rank {String(candidate.rank)}</StatusBadge> <StatusBadge>{String(candidate.validation_state)}</StatusBadge></div><h2>{String(candidate.rationale)}</h2><dl><dt>Target metric</dt><dd>{String(candidate.target_metric_key)}</dd><dt>Expected direction</dt><dd>{String(candidate.expected_direction)}</dd><dt>Feasibility</dt><dd>{String(candidate.feasibility)}</dd><dt>Measurement readiness</dt><dd>{String(candidate.measurement_readiness)}</dd></dl><button disabled={pending} onClick={() => decide("accept", String(candidate.id))}>Accept candidate → create draft</button></article>)}</section><button className="danger" disabled={pending} onClick={() => decide("reject")}>Reject recommendation</button></>;
}

export function InterventionApproval({id}: {id: string}) {
  const [data, setData] = useState<Resource>(); const [error, setError] = useState<string>(); const [message, setMessage] = useState<string>(); const [pending, setPending] = useState(false);
  const load = useCallback(() => api<Resource>(`/api/v1/interventions/${id}?${siteScope()}`).then(setData).catch((value: Error) => setError(value.message)), [id]); useEffect(() => { void load(); }, [load]);
  async function transition(action: "propose" | "approve" | "reject") { setPending(true); try { const result = await api<{status: string}>(`/api/v1/interventions/${id}/${action}?${siteScope()}`, {method: "POST", body: JSON.stringify({actor: "local-operator", reason: `WORKBENCH_${action.toUpperCase()}`, expected_updated_at: data?.data.updated_at})}); setMessage(`Intervention is now ${result.status}. No execution was started.`); await load(); } catch (value) { setError((value as Error).message); } finally { setPending(false); } }
  if (error) return <ErrorState message={error}/>; if (!data) return <LoadingState/>; const status = String(data.data.status);
  return <><PageHeader eyebrow="Intervention decision" title={String(data.data.title ?? "Intervention")} description="Approval is explicit and remains separate from recommendation acceptance and execution."/><div className="approval"><div><h2>Decision context</h2><dl><dt>Status</dt><dd><StatusBadge>{status}</StatusBadge></dd><dt>Feasibility</dt><dd>{String(data.data.feasibility ?? "Unknown")}</dd><dt>Measurement readiness</dt><dd>{String(data.data.measurement_readiness ?? "Unknown")}</dd><dt>Constraints</dt><dd>{JSON.stringify(data.data.constraints_json ?? [])}</dd><dt>Risk</dt><dd>{JSON.stringify(data.data.risk_json ?? [])}</dd></dl></div><div className="decisionPanel"><strong>Separate operator approval</strong><p>Approval authorizes the intervention lifecycle only. GIS will not execute or mutate a customer system.</p>{message && <p role="status">{message}</p>}{status === "DRAFT" && <button disabled={pending} onClick={() => transition("propose")}>Propose for approval</button>}{status === "PROPOSED" && <><button disabled={pending} onClick={() => transition("approve")}>Approve intervention</button><button className="danger" disabled={pending} onClick={() => transition("reject")}>Reject intervention</button></>}</div></div></>;
}
