"use client";

import Link from "next/link";
import {useCallback, useEffect, useState} from "react";
import {api, siteScope} from "@/lib/api";
import type {Page, Resource} from "@/lib/types";
import {EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge} from "./ui";

// API decision read-models are intentionally heterogeneous and version-tolerant.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyRow = Record<string, any>;
const text = (value: unknown) => value == null || value === "" ? "Not recorded" : String(value);
const list = (value: unknown) => Array.isArray(value) ? value : [];

function DecisionForm({buttons, onSubmit}: {buttons: [string,string][]; onSubmit: (decision:string, actor:string, comment:string)=>Promise<void>}) {
  const [actor,setActor]=useState(""); const [comment,setComment]=useState(""); const [busy,setBusy]=useState(false);
  return <div className="decisionForm"><label>Reviewer<input value={actor} onChange={e=>setActor(e.target.value)} placeholder="Your name"/></label><label>Decision note<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Document the judgment and any conditions."/></label><div>{buttons.map(([decision,label])=><button className={decision==="REJECTED"?"danger":undefined} disabled={busy||!actor.trim()} key={decision} onClick={async()=>{setBusy(true);try{await onSubmit(decision,actor,comment);}finally{setBusy(false)}}}>{label}</button>)}</div></div>;
}

function Section({label,title,children}: {label:string;title:string;children:React.ReactNode}) {return <section className="intelligenceSection"><p className="eyebrow">{label}</p><h2>{title}</h2>{children}</section>}
function Facts({data, keys}: {data:AnyRow;keys:string[]}) {return <dl className="factGrid">{keys.map(key=><div key={key}><dt>{key.replaceAll("_"," ")}</dt><dd>{text(data[key])}</dd></div>)}</dl>}
function Bullets({value}: {value:unknown}) {const items=list(value);return items.length?<ul>{items.map((item,i)=><li key={i}>{text(item)}</li>)}</ul>:<p className="muted">None recorded.</p>}
function ContextRows({title,value}:{title:string;value:unknown}) {const rows=list(value);return rows.length?<div className="sourceRecord"><h3>{title}</h3>{rows.map((row:AnyRow,i)=><pre key={row.observation_id??row.gap_id??i}>{JSON.stringify(row,null,2)}</pre>)}</div>:null}

export function OpportunityDecisionDetail({id}:{id:string}) {
  const [resource,setResource]=useState<Resource>(); const [error,setError]=useState<string>();
  const load=useCallback(()=>api<Resource>(`/api/v1/opportunities/${id}?${siteScope()}`).then(setResource).catch((e:Error)=>setError(e.message)),[id]);
  useEffect(()=>{load()},[load]);
  if(error)return <ErrorState message={error}/>; if(!resource)return <LoadingState/>;
  const d=resource.data as AnyRow; if(!d.governed_intelligence)return <EmptyState title="This is a deterministic opportunity" detail="Governed semantic decision controls appear only for Epic 27 LLM candidates."/>;
  const inference=d.model_inference as AnyRow; const decision=d.human_decision as AnyRow|null; const actions=d.actions as AnyRow; const context=d.evidence_context as AnyRow|null;
  return <><PageHeader eyebrow="Human decision gate" title={text(d.title)} description="Review authoritative evidence separately from model interpretation before allowing downstream recommendation work."/>
    <div className="trustBoundary"><span>Authoritative evidence</span><b>→</b><span>Untrusted model inference</span><b>→</b><span>Human decision</span></div>
    <Section label="Authoritative GIS data" title="Evidence packet">{context&&<><Facts data={context.entity_context??{}} keys={["canonical_key","entity_type","country_code","language_code","device"]}/><Facts data={context.market_context??{}} keys={["name","country_code","language_code","device"]}/><ContextRows title="Historical demand" value={context.demand}/><ContextRows title="Organic visibility" value={context.organic_visibility}/><ContextRows title="Search Console" value={context.search_console}/><ContextRows title="Engagement (low volume)" value={context.engagement}/><ContextRows title="Existing VAHomeMath surfaces" value={context.owned_surfaces}/><ContextRows title="Evidence quality" value={context.quality}/><ContextRows title="Evidence gaps" value={context.evidence_gaps}/></>}{list(d.authoritative_evidence).map((e:AnyRow)=><article className="evidenceCard" key={e.id}><Facts data={e} keys={["condition_key","classification","sufficiency","period_start","period_end","independent_source_count"]}/><details><summary>Technical source lineage</summary><pre>{JSON.stringify(e.items,null,2)}</pre></details></article>)}</Section>
    <Section label="Model inference — not fact" title="Semantic interpretation"><p className="lead">{text(inference.summary)}</p><Facts data={inference} keys={["problem_or_signal","reasoning","expected_value","confidence","suggested_action"]}/><h3>Assumptions</h3><Bullets value={inference.assumptions_json}/><h3>Known limitations</h3><Bullets value={d.limitations_json}/></Section>
    <Section label="Human governance" title="Opportunity review">{decision?<div className="decisionRecord"><StatusBadge>{text(decision.decision)}</StatusBadge><p>{text(decision.comment)}</p><small>{text(decision.reviewer)} · {text(decision.reviewed_at)}</small></div>:<p>No human decision has been recorded.</p>}<DecisionForm buttons={[["ACCEPTED","Accept for recommendation"],["NEEDS_REVIEW","Needs more review"],["REJECTED","Reject"]]} onSubmit={async(decision,actor,comment)=>{await api(`/api/v1/opportunities/${id}/intelligence-review?${siteScope()}`,{method:"POST",body:JSON.stringify({decision,actor,comment})});await load()}}/>
    {actions.can_generate_recommendation&&<button onClick={async()=>{await api(`/api/v1/opportunities/${id}/replay-recommendations?${siteScope()}`,{method:"POST"});await load()}}>Generate recommendation with Replay (free)</button>}<p className="providerNotice">Replay is deterministic and free. Live providers are never available from this browser action.</p></Section>
    {list(d.recommendations).length>0&&<Section label="Downstream artifact" title="Recommendations">{list(d.recommendations).map((r:AnyRow)=><p key={r.id}><Link href={`/recommendations/${r.id}`}>{text(r.model_recommendation?.title??r.summary)}</Link> <StatusBadge>{text(r.status)}</StatusBadge></p>)}</Section>}
    <details className="technical"><summary>Technical audit details</summary><pre>{JSON.stringify({llm_run:d.llm_run,decision_history:d.decision_history},null,2)}</pre></details></>;
}

export function RecommendationInbox(){const [data,setData]=useState<Page<AnyRow>>();const [error,setError]=useState<string>();useEffect(()=>{api<Page<AnyRow>>(`/api/v1/recommendations?${siteScope()}`).then(setData).catch((e:Error)=>setError(e.message))},[]);return <><PageHeader eyebrow="Decision queue" title="Recommendations" description="Model-proposed actions grounded in accepted opportunities. Selection authorizes proposal drafting, not implementation."/>{error?<ErrorState message={error}/>:!data?<LoadingState/>:data.items.length===0?<EmptyState title="No governed recommendations await review." detail="Accept an intelligence opportunity, then explicitly generate a free replay recommendation from its detail page."/>:<div className="cardList">{data.items.map(r=><article className="candidate" key={r.id}><StatusBadge>{text(r.status)}</StatusBadge><h2><Link href={`/recommendations/${r.id}`}>{text(r.model_recommendation?.title??r.summary)}</Link></h2><p>{text(r.summary)}</p><small>{list(r.opportunity_ids).length} accepted opportunity · {list(r.evidence_ids).length} evidence record</small></article>)}</div>}</>}

export function RecommendationDecisionDetail({id}:{id:string}){const [resource,setResource]=useState<Resource>();const [error,setError]=useState<string>();const load=useCallback(()=>api<Resource>(`/api/v1/recommendations/${id}?${siteScope()}`).then(setResource).catch((e:Error)=>setError(e.message)),[id]);useEffect(()=>{load()},[load]);if(error)return <ErrorState message={error}/>;if(!resource)return <LoadingState/>;const d=resource.data as AnyRow;const m=d.model_recommendation as AnyRow;if(!d.governed_intelligence)return <EmptyState title="Legacy recommendation" detail="This record uses the earlier candidate-review workflow."/>;return <><PageHeader eyebrow="Model recommendation — human selection required" title={text(m.title)} description={text(d.summary)}/><Section label="Proposed action" title="Recommendation"><p className="lead">{text(m.recommended_action)}</p><Facts data={m} keys={["rationale","expected_impact","confidence","priority","estimated_effort"]}/><h3>Assumptions</h3><Bullets value={d.assumptions_json}/><h3>Success signals</h3><Bullets value={m.success_signals_json}/><h3>Risks</h3><Bullets value={m.risks_json}/><h3>Dependencies</h3><Bullets value={m.dependencies_json}/><h3>Supporting opportunities</h3>{list(d.supporting_opportunities).map((o:AnyRow)=><p key={o.id}><Link href={`/opportunities/${o.id}`}>{text(o.title)}</Link></p>)}<h3>Supporting evidence</h3>{list(d.supporting_evidence).map((e:AnyRow)=><p key={e.id}><Link href={`/evidence/${e.id}`}>{text(e.condition_key)}</Link> · {text(e.classification)} · {text(e.period_start)} to {text(e.period_end)}</p>)}</Section><Section label="Human governance" title="Selection">{list(d.human_decisions).map((x:AnyRow)=><div className="decisionRecord" key={x.id}><StatusBadge>{text(x.decision)}</StatusBadge><p>{text(x.comment)}</p><small>{text(x.reviewer)} · {text(x.reviewed_at)}</small></div>)}{d.actions.can_select&&<DecisionForm buttons={[["SELECTED","Select for proposal"]]} onSubmit={async(_,actor,comment)=>{await api(`/api/v1/recommendations/${id}/select?${siteScope()}`,{method:"POST",body:JSON.stringify({actor,reason:comment})});await load()}}/>}{d.actions.can_generate_proposal&&<button onClick={async()=>{await api(`/api/v1/recommendations/${id}/replay-experiment-proposal?${siteScope()}`,{method:"POST"});await load()}}>Draft experiment proposal with Replay (free)</button>}<p className="providerNotice">Selection does not approve or create an intervention. Replay generation makes zero paid calls.</p></Section>{list(d.experiment_proposals).map((p:AnyRow)=><p key={p.id}><Link href={`/experiment-proposals/${p.id}`}>Open experiment proposal: {text(p.title)}</Link></p>)}<details className="technical"><summary>Lineage and LLM audit</summary><pre>{JSON.stringify({opportunity_ids:d.opportunity_ids,evidence_ids:d.evidence_ids,llm_run:d.llm_run},null,2)}</pre></details></>}

export function ProposalInbox(){const [data,setData]=useState<Page<AnyRow>>();useEffect(()=>{api<Page<AnyRow>>(`/api/v1/experiment-proposals?${siteScope()}`).then(setData)},[]);return <><PageHeader eyebrow="Pre-execution artifacts" title="Experiment proposals" description="Test plans awaiting human review. A proposal is not an experiment and does not mutate VAHomeMath."/>{!data?<LoadingState/>:data.items.length===0?<EmptyState title="No experiment proposals yet." detail="Select a governed recommendation and explicitly draft a provider-free replay proposal."/>:<div className="cardList">{data.items.map(p=><article className="candidate" key={p.id}><StatusBadge>{text(p.status)}</StatusBadge><h2><Link href={`/experiment-proposals/${p.id}`}>{text(p.title)}</Link></h2><p>{text(p.objective)}</p></article>)}</div>}</>}

export function ProposalDetail({id}:{id:string}){const [resource,setResource]=useState<Resource>();const load=useCallback(()=>api<Resource>(`/api/v1/experiment-proposals/${id}?${siteScope()}`).then(setResource),[id]);useEffect(()=>{load()},[load]);if(!resource)return <LoadingState/>;const d=resource.data as AnyRow;return <><PageHeader eyebrow="Proposed experiment — not execution" title={text(d.title)} description={text(d.objective)}/><Section label="Test design" title="Hypothesis and treatment"><p className="lead">{text(d.hypothesis)}</p><Facts data={d} keys={["target_surface","target_url_or_resource","control_description","treatment_description","primary_metric","expected_direction","expected_effect_description","evaluation_window","minimum_observation_guidance","decision_rule","rollback_plan"]}/><h3>Secondary metrics</h3><Bullets value={d.secondary_metrics_json}/><h3>Implementation steps</h3><Bullets value={d.implementation_steps_json}/><h3>Guardrails</h3><Bullets value={d.guardrail_metrics_json}/><h3>Instrumentation</h3><Bullets value={d.instrumentation_requirements_json}/><h3>Dependencies</h3><Bullets value={d.dependencies_json}/><h3>Risks</h3><Bullets value={d.risks_json}/></Section><Section label="Traceable lineage" title="Why this proposal exists"><p><Link href={`/recommendations/${d.recommendation_id}`}>Open supporting recommendation: {text(d.recommendation?.model_recommendation?.title)}</Link></p>{list(d.recommendation?.supporting_opportunities).map((o:AnyRow)=><p key={o.id}><Link href={`/opportunities/${o.id}`}>Open supporting opportunity: {text(o.title)}</Link></p>)}{list(d.recommendation?.supporting_evidence).map((e:AnyRow)=><p key={e.id}><Link href={`/evidence/${e.id}`}>Open authoritative evidence: {text(e.condition_key)}</Link></p>)}</Section><Section label="Human governance" title="Proposal review">{list(d.human_decisions).map((x:AnyRow)=><div className="decisionRecord" key={x.id}><StatusBadge>{text(x.decision)}</StatusBadge><p>{text(x.comment)}</p><small>{text(x.reviewer)} · {text(x.reviewed_at)}</small></div>)}<DecisionForm buttons={[["APPROVED","Approve proposal"],["NEEDS_REVIEW","Needs more review"],["REJECTED","Reject proposal"]]} onSubmit={async(decision,actor,comment)=>{await api(`/api/v1/experiment-proposals/${id}/review?${siteScope()}`,{method:"POST",body:JSON.stringify({decision,actor,comment})});await load()}}/><p className="providerNotice">Approval records a review only. It does not create an intervention or execute a change.</p></Section><details className="technical"><summary>Full lineage</summary><pre>{JSON.stringify(d.lineage,null,2)}</pre></details></>}

export function InterventionInbox(){return <><PageHeader eyebrow="Execution boundary" title="Interventions" description="Approved, executable changes appear here only after the separate intervention workflow."/><EmptyState title="No intervention was created by Epic 27 intelligence." detail="Evidence, opportunities, recommendations, and experiment proposals are decision artifacts. Even an approved proposal does not automatically become an intervention."/></>}
