"use client";
import {useState} from "react";
import {api,siteScope} from "../lib/api";
import {operationalLabel} from "../lib/operations";
type Choice={search_market?:{location_code:number|null;language_code:string|null}|null;id:string;capability_key:string;capability_name:string;target:string;cadence:string;default_selected:boolean};
type Preview={choices:Choice[];scope:Choice[];capabilities:number;targets:number;requests:number;estimated_cost:string|null;fingerprint:string;blockers:string[];warnings:string[];queued:number};
export function ManualExecution({providerKey,onQueued}:{providerKey:string;onQueued:()=>Promise<void>}){
 const[choices,setChoices]=useState<Choice[]>();const[selected,setSelected]=useState<string[]>([]);const[preview,setPreview]=useState<Preview>();const[requestId,setRequestId]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 async function request(mode:"select"|"preview"|"confirm"){
  setBusy(true);setError("");
  const id=mode==="select"?crypto.randomUUID():requestId;
  try{const result=mode==="select"?await api<Preview>(`/api/v1/providers/${providerKey}/manual-scope?${siteScope()}`):await api<Preview>(`/api/v1/providers/${providerKey}/run?${siteScope()}`,{method:"POST",body:JSON.stringify({request_id:id,target_ids:selected,confirmed:mode==="confirm",fingerprint:mode==="confirm"?preview?.fingerprint:""})});
   if(mode==="select"){if(!Array.isArray(result.choices))throw new Error("Manual scope API is incompatible. Restart the GIS API and Workbench together, then reload.");setRequestId(id);setChoices(result.choices);setSelected([]);setPreview(undefined);setMessage("")}
   else if(mode==="preview")setPreview(result);
   else{setChoices(undefined);setPreview(undefined);setMessage(`${result.queued} selected target executions queued. Current controls are rechecked before collection.`);await onQueued()}
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 return <section aria-label="Manual execution"><button className="secondaryButton" disabled={busy} onClick={()=>void request("select")}>Preview manual run</button>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{choices&&<div className="providerSection"><h2>Manual collection scope</h2><p>Only selected targets will execute. Scheduled targets are not selected automatically.</p>{[...new Set(choices.map(c=>c.capability_key))].map(key=><fieldset key={key}><legend>{choices.find(c=>c.capability_key===key)?.capability_name}</legend>{choices.filter(c=>c.capability_key===key).map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} disabled={busy} onChange={e=>{setSelected(ids=>e.target.checked?[...ids,c.id]:ids.filter(id=>id!==c.id));setPreview(undefined)}}/>{c.target} — {operationalLabel(c.cadence)}{c.cadence==="MANUAL_ONLY"?" · Not scheduled":" · Manual selection adds work outside the schedule"}</label>)}</fieldset>)}{choices.length===0&&<p>No authorized executable targets.</p>}<div className="providerToolbar"><button className="secondaryButton" onClick={()=>{setChoices(undefined);setPreview(undefined)}} disabled={busy}>Cancel manual collection</button><button disabled={busy||selected.length===0} onClick={()=>void request("preview")}>Review selected collection</button></div>{preview&&<section aria-label="Manual run preview"><h3>Confirm manual collection</h3><p>{preview.capabilities} {preview.capabilities===1?"capability":"capabilities"} · {preview.targets} {preview.targets===1?"target":"targets"} · {preview.requests} provider {preview.requests===1?"request":"requests"}</p><ul>{preview.scope.map(c=><li key={c.id}>{c.capability_name} — {c.target}{c.search_market&&<> · Search market: location {c.search_market.location_code??"not configured"}, language {c.search_market.language_code??"not configured"}</>}</li>)}</ul><p>Estimated cost: {preview.estimated_cost===null?"Unknown":`$${preview.estimated_cost}`} · Maximum requests: {preview.requests}</p><p>Authorization, rights, credential, pause and budget controls still apply. Schedules are unchanged.</p>{preview.blockers.map(b=><p role="alert" key={b}>{operationalLabel(b)}</p>)}{preview.warnings?.map(w=><p key={w}>{operationalLabel(w)}</p>)}<button disabled={busy||preview.blockers.length>0||preview.requests===0} onClick={()=>void request("confirm")}>Confirm and queue collection</button></section>}</div>}</section>
}
