import Link from "next/link";
import type {ReactNode} from "react";
import {formatDate} from "../lib/format";
import {type Activity,duration,exactMoney,operationalLabel as label} from "../lib/operations";

export function Disclosure({title,children}:{title:string;children:ReactNode}){return <details className="operationalDisclosure"><summary>{title}</summary><div>{children}</div></details>}
export function Summary({items}:{items:Array<[string,ReactNode]>}){return <dl className="operationalSummary">{items.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value??"Unknown"}</dd></div>)}</dl>}
export function Cost({item}:{item:Activity}){return <span>{exactMoney(item.provider_cost_exact,item.currency)} {item.provider_cost_exact!==null?"actual":"— cost unknown"}{item.provider_cost_exact!==null&&<small>Currency-rounded: {exactMoney(item.provider_cost_display,item.currency)}</small>}</span>}
export function ActivityTable({items}:{items:Activity[]}){return items.length?<div className="activityTable"><table><caption className="sr-only">Collection activity, one row per execution obligation</caption><thead><tr><th>Collection / target</th><th>Completed / started</th><th>Outcome</th><th>Trigger / timeliness</th><th>Records</th><th>Cost</th></tr></thead><tbody>{items.map(r=><tr key={r.id}><td data-label="Collection / target"><Link href={r.href??`/system/runs/${r.id}`}>{r.label}</Link><small>{r.provider_name} · {r.target_display_name}</small></td><td data-label="Time">{formatDate(r.completed_at??r.started_at)}</td><td data-label="Outcome">{label(r.outcome)}<small>{r.attempt_count} attempts</small></td><td data-label="Execution">{label(r.trigger)}<small>{label(r.timeliness)}</small></td><td data-label="Records"><span aria-label={`${r.records_received??"Unknown"} received, ${r.records_inserted??"Unknown"} inserted`}>{r.records_received??"—"} / {r.records_inserted??"—"}</span></td><td data-label="Cost"><Cost item={r}/></td></tr>)}</tbody></table></div>:<p>No collection activity recorded.</p>}
export function AttemptTimeline({item}:{item:Activity}){return <><p>{item.recovery_summary}</p>{item.recovery_latency!=null&&<p>Recovered {duration(item.recovery_latency)} late. Idle waiting is not execution time.</p>}<ol className="attemptTimeline">{item.attempt_timeline.map(a=><li key={a.number}><strong>Attempt {a.number} — {label(a.status)}</strong><span>{formatDate(a.started_at)} · {duration(a.duration)} · {label(a.trigger)}</span>{a.resolved_cause&&<p>{label(a.resolved_cause)}</p>}<Disclosure title={`Attempt ${a.number} recorded evidence`}><p>Recorded classification: {a.recorded_classification??"None"}</p><p>Completed: {formatDate(a.completed_at)}</p><p>Recorded attempt cost: {exactMoney(a.cost,item.currency)}</p></Disclosure></li>)}</ol></>}
