"use client";

import {useEffect, useState} from "react";
import {api, siteScope} from "@/lib/api";
import {formatDate, formatNumber} from "@/lib/format";
import type {Overview} from "@/lib/types";
import {ErrorState, LoadingState, MetricCard, PageHeader} from "./ui";

export function OverviewPage() {
  const [data, setData] = useState<Overview>(); const [error, setError] = useState<string>();
  useEffect(() => { api<Overview>(`/api/v1/overview?${siteScope()}`).then(setData).catch((value: Error) => setError(value.message)); }, []);
  return <><PageHeader eyebrow="VAHomeMath · Growth intelligence" title="Intelligence overview" description="Current stored evidence, governed intelligence, and the decisions it can support."/>{error ? <ErrorState message={error}/> : !data ? <LoadingState/> : <>
    <h2>Decision workflow</h2><section className="metrics"><MetricCard label="Opportunities to review" value={data.opportunities_to_review} detail="Evidence-supported conditions"/><MetricCard label="Recommendations to review" value={data.recommendations_to_review} detail="Human decision required"/><MetricCard label="Interventions to approve" value={data.interventions_to_approve} detail="Separate approval boundary"/><MetricCard label="Active interventions" value={data.active_interventions} detail="Approved or underway"/><MetricCard label="Experiments running" value={data.experiments_running} detail="Measurement plans"/><MetricCard label="Observed outcomes" value={data.recent_outcomes} detail="Not causal impact"/></section>
    <h2>Search &amp; traffic</h2><section className="metrics"><MetricCard label="Current GSC observations" value={data.search.stored_observations} detail={`Effective records · latest ${formatDate(data.search.latest_observation)}`}/><MetricCard label="GSC impressions" value={data.search.impressions ? formatNumber(data.search.impressions) : "Unknown"} detail={data.search.rights_state === "USABLE" ? "Measured" : "Rights review required"}/><MetricCard label="GSC clicks" value={data.search.clicks ? formatNumber(data.search.clicks) : "Unknown"} detail={data.search.rights_state === "USABLE" ? "Measured" : "Rights review required"}/><MetricCard label="Stored GA4 events" value={data.traffic.stored_event_observations} detail={`Latest ${formatDate(data.traffic.latest_observation)}`}/><MetricCard label="GA4 sessions" value={data.traffic.sessions ? formatNumber(data.traffic.sessions) : "Unknown"} detail={data.traffic.rights_state === "USABLE" ? "Measured" : "Rights review required"}/><MetricCard label="Landing-page observations" value={data.traffic.stored_landing_page_observations} detail="Stored, governed records"/></section>
    {(data.search.blocker || data.traffic.blocker) && <section className="notice"><strong>Rights-limited metrics</strong><p>Stored GSC and GA4 evidence is present, but customer display and aggregation remain fail-closed until the attached rights policy is explicitly reviewed. Missing metrics are Unknown, not zero.</p></section>}
    <h2>Visibility, market &amp; demand</h2><section className="metrics"><MetricCard label="Stored SERP results" value={data.visibility.stored_serp_results} detail={`Across only ${data.visibility.stored_serp_observations} observation; longitudinal coverage is thin`}/><MetricCard label="Active market" value={data.market.name ?? "Unknown"} detail={`Version ${data.market.version ?? "Unknown"}`} href={data.market.id ? `/markets/${data.market.id}` : undefined}/><MetricCard label="Market members" value={data.market.definition_member_count} detail="Frozen definition members"/><MetricCard label="Stored provider keywords" value={data.demand.stored_external_keywords} detail="DataForSEO · stored data only"/><MetricCard label="Demand observations" value={data.demand.demand_observations} detail={data.demand.rights_state === "USABLE" ? "Provider-specific" : "Rights blocked"}/><MetricCard label="Demand signals" value={data.demand.demand_signals} detail="Deterministic analysis output"/></section>
    <h2>Evidence &amp; competitive intelligence</h2><section className="metrics"><MetricCard label="Evidence packages" value={data.evidence.packages} detail={data.evidence.status} href="/evidence"/><MetricCard label="Evidence gaps" value={data.evidence.gaps} detail="Explicit collection needs" href="/evidence"/><MetricCard label="Competitive content" value={data.competitive.content_observations} detail="Governed observations"/><MetricCard label="Technology detections" value={data.competitive.technology_detections} detail="Deterministic detections"/><MetricCard label="Competitive events" value={data.competitive.events} detail={`Latest ${formatDate(data.competitive.latest_event)}`}/><MetricCard label="Market observations" value={data.market.observation_count} detail="Governed market snapshots"/></section>
    {data.evidence.packages === 0 && <section className="notice"><strong>Why opportunities remain empty</strong><p>{data.evidence.explanation} Without a rights-usable evidence package, deterministic opportunity detectors correctly produce no opportunities or recommendations.</p></section>}
    <h2>Collection health</h2><section className="metrics"><MetricCard label="Collection targets" value={data.collection_health.targets} detail={`Updated ${formatDate(data.collection_health.latest_update)}`} href="/collection"/><MetricCard label="Query targets" value={data.collection_health.query_targets} detail="Governed query identities" href="/collection?target_type=QUERY"/><MetricCard label="Domain targets" value={data.collection_health.domain_targets} detail="Governed domains" href="/collection?target_type=DOMAIN"/><MetricCard label="URL targets" value={data.collection_health.url_targets} detail="Governed URLs" href="/collection?target_type=URL"/></section>
    <section className="notice"><strong>Governed workflow</strong><p>Recommendation acceptance creates a draft. Intervention approval is a separate operator decision, and approval still does not execute anything automatically.</p></section>
  </>}</>;
}
