"use client";

import Link from "next/link";
import {useEffect, useState} from "react";
import {api, siteScope} from "@/lib/api";
import {formatDate, formatNumber, humanize} from "@/lib/format";
import {ErrorState, LoadingState, PageHeader, StatusBadge} from "./ui";

type Value = unknown; type Detail = Record<string, Value>;
function isTechnical(key: string): boolean { return key === "id" || key === "href" || key.endsWith("_id") || key.endsWith("_uuid") || key.includes("identity_hash") || key === "resource_type" || key === "evidence_identifier" || key === "evidence_key"; }
function Scalar({name, value}: {name: string; value: Value}) { const isDate = /(_at|_date|_start|_end|last_success|latest_success|fresh_through)$/.test(name); const numeric = typeof value === "number" || /^-?\d+(?:\.\d+)?(?:e[+-]?\d+)?$/i.test(String(value ?? "")); const rendered = isDate ? formatDate(value) : numeric ? formatNumber(value, "decimal") : String(value ?? "Unknown"); return <div><dt>{humanize(name)}</dt><dd>{typeof value === "string" && value.startsWith("/") ? <Link href={value}>{rendered}</Link> : rendered}</dd></div>; }
function Section({name, value}: {name: string; value: Value}) { if (value === null || value === undefined || (Array.isArray(value) && !value.length)) return null; if (typeof value !== "object") return null; const advanced = /provenance|metadata|technical/.test(name); if (Array.isArray(value) && value.every((item) => typeof item !== "object")) return <section className="semanticSection"><h2>{humanize(name)}</h2><ul>{value.map((item, index) => <li key={`${String(item)}-${index}`}>{String(item)}</li>)}</ul></section>; if (Array.isArray(value)) return <section className="semanticSection"><h2>{humanize(name)}</h2><div className="recordGrid">{value.map((item, index) => <article className="recordCard" key={String((item as Detail).id ?? index)}>{Object.entries(item as Detail).filter(([key, entry]) => typeof entry !== "object" && (advanced || !isTechnical(key))).slice(0, 8).map(([key, entry]) => <Scalar key={key} name={key} value={entry}/>)}</article>)}</div></section>; return <section className="semanticSection"><h2>{humanize(name)}</h2><dl className="detailGrid">{Object.entries(value as Detail).filter(([key, entry]) => typeof entry !== "object" && (advanced || !isTechnical(key))).map(([key, entry]) => <Scalar key={key} name={key} value={entry}/>)}</dl>{Object.entries(value as Detail).filter(([, entry]) => typeof entry === "object").map(([key, entry]) => <Section key={key} name={key} value={entry}/>)}</section>; }
export function SemanticDetail({endpoint, eyebrow, fallback}: {endpoint: string; eyebrow: string; fallback: string}) { const [data, setData] = useState<Detail>(); const [error, setError] = useState<string>(); useEffect(() => { api<Detail>(`${endpoint}?${siteScope()}`).then((payload) => setData((payload.data as Detail) ?? payload)).catch((value: Error) => setError(value.message)); }, [endpoint]); if (error) return <ErrorState message={error}/>; if (!data) return <LoadingState/>; const label = String(data.label ?? fallback); return <><nav className="breadcrumbs" aria-label="Breadcrumb"><Link href="/">Overview</Link><span>→</span><span>{eyebrow}</span><span>→</span><strong>{label}</strong></nav><PageHeader eyebrow={eyebrow} title={label} description={String(data.description ?? "Governed GIS intelligence object.")}/>{data.status && typeof data.status === "string" ? <StatusBadge>{String(data.status)}</StatusBadge> : null}{data.why_it_matters ? <div className="notice"><strong>Why this matters</strong><p>{String(data.why_it_matters)}</p></div> : null}<dl className="detailGrid">{Object.entries(data).filter(([key, value]) => !["label", "description", "why_it_matters"].includes(key) && typeof value !== "object" && !isTechnical(key)).map(([key, value]) => <Scalar key={key} name={key} value={value}/>)}</dl>{Object.entries(data).filter(([, value]) => typeof value === "object").map(([key, value]) => <Section key={key} name={key} value={value}/>)}</>; }
