"use client";

import Link from "next/link";
import {useEffect, useState} from "react";
import {api, siteScope} from "@/lib/api";
import {humanize, formatDate} from "@/lib/format";
import {ErrorState, LoadingState, PageHeader} from "./ui";

type Telemetry={execution_held?:boolean;state:string;checked_at:string|null;values:Record<string,unknown>;failure_category:string|null};
type Connection={id:string;status:string;required_rights:{label:string;status:string;required:string;blocking:boolean}[];account_telemetry:Telemetry|null;credential_readiness?:{reason?:string;execution_held?:boolean;authentication_state?:string}};
type Source={label:string;description:string;connections:Connection[];impact:{explanation:string;pipeline_links:{pipeline:string;href:string}[]}};
type Review={policy:Record<string,string|null>|null;decisions:Record<string,string>;grants:Record<string,string>;history:{id:string;policy_version:string;review_authority:string|null;reviewed_at:string|null;documented_basis:string|null;grants?:Record<string,string>}[]};

export function SourceGovernance({sourceKey}:{sourceKey:string}){
 const[data,setData]=useState<Source>();const[error,setError]=useState<string>();const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string>();
 const load=()=>api<Source>(`/api/v1/system/sources/${sourceKey}?${siteScope()}`).then(setData);
 useEffect(()=>{api<Source>(`/api/v1/system/sources/${sourceKey}?${siteScope()}`).then(setData).catch((e:Error)=>setError(e.message));},[sourceKey]);
 async function refresh(id:string){if(!window.confirm("Refresh BuiltWith account telemetry? Official documentation states zero API credits. This contacts the provider but does not collect a domain or authorize collection."))return;setBusy(true);setMessage(undefined);try{await api(`/api/v1/connections/${id}/account-telemetry/refresh?${siteScope()}`,{method:"POST",body:JSON.stringify({actor:"Workbench operator",confirmed:true})});await load();setMessage("Account refresh completed. Inspect its state below; collection was not requested.");}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 if(error)return <ErrorState message={error}/>;if(!data)return <LoadingState/>;
 return <><PageHeader eyebrow="Source governance" title={data.label} description={data.description}/><nav className="subnav"><Link href="/system/sources">All sources</Link>{sourceKey==="builtwith"&&<><Link href="/providers/builtwith">Collection controls</Link><Link href="/docs/builtwith-governance">Rights evidence and account guide</Link></>}</nav>
 <section className="semanticSection"><h2>Dependencies and impact</h2><p>{data.impact.explanation??"Restart GIS after deployment to load detailed governance and dependency diagnostics."}</p>{(data.impact.pipeline_links??[]).map(p=><p key={p.href}><Link href={p.href}>{humanize(p.pipeline)}</Link></p>)}</section>
 {message&&<p role="status">{message}</p>}
 {!data.connections.length&&<p>No connection is configured. Rights review requires a site-scoped connection.</p>}
 {data.connections.map(c=><section className="semanticSection" key={c.id}><h2>Connection governance</h2><p>Connection: {c.status}. {c.credential_readiness?.reason}</p><p>Authentication: {humanize(c.credential_readiness?.authentication_state??"UNKNOWN")}. Collection worker hold: {c.credential_readiness?.execution_held?"Enabled":"Not reported as enabled"}.</p>
 {!!c.required_rights?.length&&<><h3>Required collection rights</h3><ul>{c.required_rights.map(r=><li key={r.label}>{r.label}: {r.status==="DENIED"?"PROHIBITED":r.status} — {r.blocking?"ALLOWED required; blocking":"sufficient"}</li>)}</ul><p>Other unknown uses do not block this collector. Rights approval does not authorize a request.</p></>}
 <RightsReview connectionId={c.id} onSaved={load}/>
 {c.account_telemetry&&<><h3>Account telemetry</h3><p>{c.account_telemetry.state} · Last checked: {formatDate(c.account_telemetry.checked_at)}</p>{c.account_telemetry.state==="UNKNOWN"&&<p>Never retrieved. Unknown is not zero.</p>}{c.account_telemetry.failure_category&&<p>Latest refresh failed: {humanize(c.account_telemetry.failure_category)}. Current balance is unavailable.</p>}<dl className="detailGrid">{Object.entries(c.account_telemetry.values).map(([k,v])=><div key={k}><dt>{humanize(k)}</dt><dd>{v===null?"Unknown":Array.isArray(v)?v.join(", ")||"None reported":String(v)}</dd></div>)}</dl><p>24-hour freshness; manual refresh only. Advertised Domain API availability is not licensed entitlement. Account privacy flags do not grant GIS rights. GIS budgets and request limits still apply.</p><button disabled={busy} onClick={()=>void refresh(c.id)}>Refresh account telemetry</button><p>Documented zero API credits. No domain collection. Account API hold: {c.account_telemetry.execution_held===undefined?"Unknown":c.account_telemetry.execution_held?"Enabled":"Not enabled"}. Global execution hold still applies.</p></>}
 </section>)}</>;
}

function RightsReview({connectionId,onSaved}:{connectionId:string;onSaved:()=>Promise<void>}){
 const[review,setReview]=useState<Review>();const[message,setMessage]=useState<string>();const[busy,setBusy]=useState(false);
 async function open(){try{setReview(await api<Review>(`/api/v1/connections/${connectionId}/rights?${siteScope()}`));setMessage(undefined)}catch(e){setMessage((e as Error).message)}}
 async function save(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!review)return;const form=new FormData(event.currentTarget);if(!window.confirm("Approve this new rights-policy version for future use of this connection? Historical policies and observations remain unchanged."))return;setBusy(true);try{const metadata=Object.fromEntries(["review_authority","documented_basis","policy_version","license_type","license_version","license_url","jurisdiction_notes","policy_notes","attribution_text"].map(k=>[k,String(form.get(k)||"")||null]));const result=await api<Review>(`/api/v1/connections/${connectionId}/rights/reviews?${siteScope()}`,{method:"POST",body:JSON.stringify({...metadata,expected_policy_id:review.policy?.id??null,effective_at:new Date().toISOString(),decisions:review.decisions,grants:review.grants,retention_days:form.get("retention_days")===""?null:Number(form.get("retention_days"))})});setReview(result);await onSaved();setMessage("New policy version approved. No collection was queued.");}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <><button className="secondaryButton" onClick={()=>void open()}>Review rights</button>{message&&<p role="status">{message}</p>}{review&&<form onSubmit={e=>void save(e)}><h3>Human rights review</h3><p>UNKNOWN is not permission. Review each field; no recommendation is pre-approved. Effective permitted-use grants below take precedence over the compatibility fields. This review is effective now and affects only this connection, not historical evidence or other connections.</p>
 <details><summary>Compatibility policy fields</summary><div className="detailGrid">{Object.entries(review.decisions).map(([key,value])=><label key={key}>{humanize(key)}<select value={value} onChange={e=>setReview({...review,decisions:{...review.decisions,[key]:e.target.value}})}>{["UNKNOWN","ALLOWED","PROHIBITED"].map(v=><option key={v}>{v}</option>)}</select></label>)}</div></details>
 <h4>Effective permitted uses</h4><p>Raw retention and normalized retention are the two required BuiltWith uses. DENIED is the grant equivalent of PROHIBITED.</p><div className="detailGrid">{Object.entries(review.grants).map(([key,value])=><label key={key}>{humanize(key)}<select value={value} onChange={e=>setReview({...review,grants:{...review.grants,[key]:e.target.value}})}><option>UNKNOWN</option><option>ALLOWED</option><option value="DENIED">PROHIBITED</option></select></label>)}</div>
 <div className="detailGrid">{["review_authority","policy_version","documented_basis","license_type","license_version","license_url","jurisdiction_notes","policy_notes","attribution_text"].map(k=><label key={k}>{humanize(k)}<input name={k} required={["review_authority","policy_version","documented_basis"].includes(k)} defaultValue={k==="policy_version"?"":review.policy?.[k]??""}/></label>)}<label>Retention days (blank = unknown)<input name="retention_days" type="number" min="0" defaultValue={review.policy?.retention_days??""}/></label></div>
 <button disabled={busy} type="submit">Approve new policy version</button><button type="button" className="secondaryButton" onClick={()=>setReview(undefined)}>Cancel review</button><details><summary>Policy review history ({review.history.length})</summary>{review.history.map(p=><p key={p.id}>{p.policy_version} · {p.review_authority??"Unreviewed"} · {formatDate(p.reviewed_at)} · {p.documented_basis}<span>{Object.entries(p.grants??{}).map(([use,state])=><small style={{display:"block"}} key={use}>{humanize(use)}: {state==="DENIED"?"PROHIBITED":state}</small>)}</span></p>)}</details></form>}</>;
}
