"use client";

import Link from "next/link";
import {useEffect,useState} from "react";
import {api,siteScope,WorkbenchApiError} from "@/lib/api";
import {formatDate,humanize} from "@/lib/format";
import {ErrorState,LoadingState,PageHeader} from "./ui";

type Right={use?:string;label:string;status:string;required?:string;blocking:boolean};
type Connection={id:string;status:string;required_rights:Right[];credential_readiness?:{reason?:string;execution_held?:boolean;authentication_state?:string};account_telemetry?:{state:string;checked_at:string|null;values:Record<string,unknown>;failure_category:string|null;execution_held?:boolean}|null};
type Source={label:string;description:string;connections:Connection[];impact:{explanation?:string;pipeline_links?:{pipeline:string;href:string}[]}};
type Policy=Record<string,string|number|null>;
type History=Policy&{id:string;policy_version:string;review_authority?:string|null;reviewed_at?:string|null;documented_basis?:string|null;effective_at?:string|null;supersedes_policy_id?:string|null;grants?:Record<string,string>};
type Review={policy:Policy|null;decisions:Record<string,string>;grants:Record<string,string>;history:History[];required_rights?:Right[]};
type Approval={approval:{policy_id:string;version:string;effective_at:string|null;reviewed_at:string|null;supersedes_policy_id:string|null}};
type Draft={decisions:Record<string,string>;grants:Record<string,string>;review_authority:string;documented_basis:string;policy_version:string;license_type:string;license_version:string;license_url:string;jurisdiction_notes:string;policy_notes:string;attribution_text:string;retention_days:string};

const GROUPS=[
 ["A — Collection-critical rights","Both must be ALLOWED for BuiltWith TECHNOLOGY_PROFILE collection.",["raw_retention","normalized_retention"]],
 ["B — Internal and derived uses","Evaluated independently; these are not implicit collection prerequisites.",["internal_analysis","commercial_use","derivative_creation","aggregate_statistics","rag_retrieval","ai_inference"]],
 ["C — External and redistribution uses","API access does not imply publication, redistribution, display, or export rights.",["external_publication","raw_redistribution","normalized_redistribution","customer_facing_display","customer_export"]],
 ["D — Model and learning uses","AI training and cross-tenant learning remain separately governed.",["ai_training"]],
] as const;
const META:[keyof Draft,string,boolean?,boolean?,string?][]=[
 ["review_authority","Review authority",true],["policy_version","Policy version",true],["documented_basis","Documented basis",true,true],
 ["license_type","License type"],["license_version","License version"],["license_url","License URL",false,false,"url"],
 ["jurisdiction_notes","Jurisdiction notes",false,true],["attribution_text","Attribution text",false,true],
 ["retention_days","Retention days (blank means unknown)",false,false,"number"],["policy_notes","Policy notes",false,true],
];
const show=(value:string)=>value==="DENIED"?"PROHIBITED":value;
const makeDraft=(review:Review):Draft=>({decisions:{...review.decisions},grants:{...review.grants},review_authority:"",documented_basis:"",policy_version:"",license_type:String(review.policy?.license_type??""),license_version:String(review.policy?.license_version??""),license_url:String(review.policy?.license_url??""),jurisdiction_notes:String(review.policy?.jurisdiction_notes??""),policy_notes:String(review.policy?.policy_notes??""),attribution_text:String(review.policy?.attribution_text??""),retention_days:String(review.policy?.retention_days??"")});

export function SourceGovernance({sourceKey}:{sourceKey:string}){
 const[data,setData]=useState<Source>();const[error,setError]=useState<string>();const[busy,setBusy]=useState(false);const[message,setMessage]=useState<string>();
 const load=()=>api<Source>(`/api/v1/system/sources/${sourceKey}?${siteScope()}`).then(setData);
 useEffect(()=>{load().catch((e:Error)=>setError(e.message));},[sourceKey]); // eslint-disable-line react-hooks/exhaustive-deps
 async function refresh(id:string){if(!window.confirm("Refresh BuiltWith account telemetry? Official documentation states zero API credits. This contacts the provider but does not collect a domain or authorize collection."))return;setBusy(true);try{await api(`/api/v1/connections/${id}/account-telemetry/refresh?${siteScope()}`,{method:"POST",body:JSON.stringify({actor:"Workbench operator",confirmed:true})});await load();setMessage("Account refresh completed. Collection was not requested.");}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 if(error)return <ErrorState message={error}/>;if(!data)return <LoadingState/>;
 return <><PageHeader eyebrow="Source governance" title={data.label} description={data.description}/><nav className="subnav"><Link href="/system/sources">All sources</Link>{sourceKey==="builtwith"&&<><Link href="/providers/builtwith">Collection controls</Link><Link href="/docs/builtwith-governance">Rights evidence and account guide</Link></>}</nav>
 <section className="semanticSection"><h2>Dependencies and impact</h2><p>{data.impact.explanation??"Restart GIS after deployment to load detailed governance and dependency diagnostics."}</p>{(data.impact.pipeline_links??[]).map(p=><p key={p.href}><Link href={p.href}>{humanize(p.pipeline)}</Link></p>)}</section>
 {message&&<p className="governanceMessage" role="status">{message}</p>}{!data.connections.length&&<p>No connection is configured. Rights review requires a site-scoped connection.</p>}
 {data.connections.map(c=><section className="semanticSection" key={c.id}><h2>Connection governance</h2><p>Connection: {c.status}. {c.credential_readiness?.reason}</p><p>Authentication: {humanize(c.credential_readiness?.authentication_state??"UNKNOWN")}. Collection worker hold: {c.credential_readiness?.execution_held?"Enabled":"Not reported as enabled"}.</p>
 {!!c.required_rights?.length&&<><h3>Required collection rights</h3><ul>{c.required_rights.map(r=><li key={r.label}>{r.label}: {show(r.status)} — {r.blocking?"ALLOWED required; blocking":"sufficient"}</li>)}</ul><p>Other unknown uses do not block this collector. Rights approval does not authorize a request.</p></>}
 <RightsReview connectionId={c.id} requiredRights={c.required_rights??[]} onSaved={load}/>
 {c.account_telemetry&&<><h3>Account telemetry</h3><p>{c.account_telemetry.state} · Last checked: {formatDate(c.account_telemetry.checked_at)}</p>{c.account_telemetry.state==="UNKNOWN"&&<p>Never retrieved. Unknown is not zero.</p>}{c.account_telemetry.failure_category&&<p>Latest refresh failed: {humanize(c.account_telemetry.failure_category)}. Current balance is unavailable.</p>}<dl className="detailGrid">{Object.entries(c.account_telemetry.values).map(([k,v])=><div key={k}><dt>{humanize(k)}</dt><dd>{v===null?"Unknown":Array.isArray(v)?v.join(", ")||"None reported":String(v)}</dd></div>)}</dl><p>24-hour freshness; manual refresh only. Advertised Domain API availability is not licensed entitlement. Account privacy flags do not grant GIS rights. GIS budgets and request limits still apply.</p><button disabled={busy} onClick={()=>void refresh(c.id)}>Refresh account telemetry</button><p>Documented zero API credits. No domain collection. Account API hold: {c.account_telemetry.execution_held===undefined?"Unknown":c.account_telemetry.execution_held?"Enabled":"Not enabled"}. Global execution hold still applies.</p></>}
 </section>)}</>;
}

function RightsReview({connectionId,requiredRights,onSaved}:{connectionId:string;requiredRights:Right[];onSaved:()=>Promise<void>}){
 const[review,setReview]=useState<Review>();const[draft,setDraft]=useState<Draft>();const[confirm,setConfirm]=useState(false);const[message,setMessage]=useState<string>();const[errors,setErrors]=useState<Record<string,string>>({});const[busy,setBusy]=useState(false);
 async function open(){try{const value=await api<Review>(`/api/v1/connections/${connectionId}/rights?${siteScope()}`);setReview(value);setDraft(makeDraft(value));setErrors({});setMessage(undefined)}catch(e){setMessage((e as Error).message)}}
 function update(field:keyof Draft,value:string|Record<string,string>){if(!draft)return;setDraft({...draft,[field]:value});setErrors({...errors,[field]:""});}
 function validate(){if(!draft)return false;const next:Record<string,string>={};for(const key of ["review_authority","documented_basis","policy_version"] as const)if(!draft[key].trim())next[key]=`${humanize(key)} is required.`;if(draft.retention_days!==""&&!/^\d+$/.test(draft.retention_days))next.retention_days="Retention days must be zero or a positive whole number.";setErrors(next);if(Object.keys(next).length)setMessage("Correct the highlighted fields before reviewing this policy.");return !Object.keys(next).length;}
 async function approve(){if(!review||!draft)return;setBusy(true);setMessage(undefined);try{const result=await api<Approval>(`/api/v1/connections/${connectionId}/rights/reviews?${siteScope()}`,{method:"POST",body:JSON.stringify({expected_policy_id:review.policy?.id??null,effective_at:new Date().toISOString(),decisions:draft.decisions,grants:draft.grants,review_authority:draft.review_authority,documented_basis:draft.documented_basis,policy_version:draft.policy_version,license_type:draft.license_type||null,license_version:draft.license_version||null,license_url:draft.license_url||null,jurisdiction_notes:draft.jurisdiction_notes||null,policy_notes:draft.policy_notes||null,attribution_text:draft.attribution_text||null,retention_days:draft.retention_days===""?null:Number(draft.retention_days)})});const current=await api<Review>(`/api/v1/connections/${connectionId}/rights?${siteScope()}`);setReview(current);setDraft(makeDraft(current));setConfirm(false);await onSaved();setMessage(`BuiltWith rights policy version ${result.approval.version} approved. No provider request was made and no credits were spent.`);}catch(e){const error=e as Error;setMessage(e instanceof WorkbenchApiError&&e.status===409?`This review is stale or conflicts with the effective policy. ${error.message} Your entries are preserved; reload current policy before approving.`:error.message);setConfirm(false);}finally{setBusy(false)}}
 if(!review||!draft)return <><button className="secondaryButton" onClick={()=>void open()}>Review rights</button>{message&&<p className="governanceMessage error" role="alert">{message}</p>}</>;
 const requirements=(review.required_rights?.length?review.required_rights:requiredRights).map(r=>({...r,use:r.use??(r.label.toLowerCase().startsWith("raw")?"raw_retention":"normalized_retention")}));
 return <section className="rightsWorkbench" aria-labelledby="rights-title"><header className="rightsHeader"><div><p className="eyebrow">Current effective policy</p><h3 id="rights-title">Human rights review</h3><p>Version {String(review.policy?.policy_version??"Unreviewed")} stays effective until its immutable successor is committed.</p></div><button className="secondaryButton" onClick={()=>{setReview(undefined);setDraft(undefined)}}>Close review</button></header>
 {message&&<p className={`governanceMessage ${message.includes("approved")?"success":"error"}`} role={message.includes("approved")?"status":"alert"}>{message}</p>}
 {confirm?<section className="rightsConfirmation" role="dialog" aria-modal="true" aria-labelledby="confirm-title"><h3 id="confirm-title">Confirm immutable policy version {draft.policy_version}</h3><p>A new effective policy will be created and the previous version preserved. This does not execute BuiltWith, spend credits, authorize collection, or bypass manual execution controls.</p><Summary review={review} draft={draft} requirements={requirements}/><div className="rightsActions"><button className="secondaryButton" onClick={()=>setConfirm(false)}>Back to review</button><button disabled={busy} onClick={()=>void approve()}>{busy?"Approving…":"Confirm and approve new version"}</button></div></section>:
 <form className="rightsForm" noValidate onSubmit={e=>{e.preventDefault();if(validate())setConfirm(true)}}>
 {GROUPS.map(([title,detail,keys],index)=><fieldset className="rightsGroup" key={title}><legend>{title}</legend><p>{detail}</p><div className="rightsGrid">{keys.map(key=>{const current=review.grants[key]??"UNKNOWN";const critical=index===0;return <label className={`rightsCard ${critical?"critical":""}`} key={key}><span className="rightsLabel">{humanize(key)}</span><span className="rightsMeta">Current: <b>{show(current)}</b></span>{critical&&<><span className="rightsMeta">Required: <b>ALLOWED</b></span><span className={`rightsStatus ${current==="ALLOWED"?"ready":"blocked"}`}>{current==="ALLOWED"?"NON-BLOCKING":"BLOCKING"}</span></>}<select aria-label={`${humanize(key)} reviewed value`} value={draft.grants[key]} onChange={e=>update("grants",{...draft.grants,[key]:e.target.value})}><option>UNKNOWN</option><option>ALLOWED</option><option value="DENIED">PROHIBITED</option></select></label>})}</div></fieldset>)}
 <fieldset className="rightsGroup"><legend>Compatibility policy controls</legend><p>Canonical compatibility decisions remain explicit. Effective permitted-use grants above take precedence.</p><div className="rightsGrid compact">{Object.entries(draft.decisions).map(([key,value])=><label className="rightsControl" key={key}><span>{humanize(key)}</span><select value={value} onChange={e=>update("decisions",{...draft.decisions,[key]:e.target.value})}><option>UNKNOWN</option><option>ALLOWED</option><option>PROHIBITED</option></select></label>)}</div></fieldset>
 <fieldset className="rightsGroup evidence"><legend>E — Policy evidence and review metadata</legend><div className="evidenceGrid">{META.map(([name,label,required,multiline,type])=><label className={`evidenceField ${multiline?"wide":""}`} key={name} htmlFor={`rights-${name}`}><span>{label}{required&&" *"}</span>{multiline?<textarea id={`rights-${name}`} value={String(draft[name])} aria-invalid={!!errors[name]} onChange={e=>update(name,e.target.value)}/>:<input id={`rights-${name}`} type={type??"text"} min={type==="number"?0:undefined} value={String(draft[name])} aria-invalid={!!errors[name]} onChange={e=>update(name,e.target.value)}/>} {errors[name]&&<small className="fieldError">{errors[name]}</small>}</label>)}</div></fieldset>
 <Summary review={review} draft={draft} requirements={requirements}/><div className="rightsActions"><button type="submit">Review proposed policy</button><button type="button" className="secondaryButton" onClick={()=>setDraft(makeDraft(review))}>Discard proposed changes</button></div></form>}
 <HistoryView history={review.history}/></section>;
}

function Summary({review,draft,requirements}:{review:Review;draft:Draft;requirements:Right[]}){const changes=Object.entries(draft.grants).filter(([key,value])=>value!==review.grants[key]);return <section className="rightsSummary"><h4>Proposed policy changes</h4>{changes.length?<ul>{changes.map(([key,value])=><li key={key}>{humanize(key)}: {show(review.grants[key]??"UNKNOWN")} → {show(value)}</li>)}</ul>:<p>No permitted-use grant changes yet.</p>}<h4>Collection impact</h4><ul>{requirements.map(r=><li key={r.use}>{r.label} blocker: {r.blocking?(draft.grants[r.use??""]==="ALLOWED"?"will resolve":"will remain"):"already resolved"}</li>)}</ul><p>Expected readiness reflects rights only. Credentials, authentication evidence, authorization, target scope, budget, limits, the global hold, preview, and explicit manual confirmation remain separate controls.</p></section>}

function HistoryView({history}:{history:History[]}){return <section className="policyHistory"><h3>Policy review history ({history.length})</h3><p>Newest effective policy first. Historical versions are immutable audit evidence.</p>{history.map((p,index)=><details className="historyCard" key={p.id} open={index===0}><summary><span>Version {p.policy_version}</span><b>{index===0?(p.reviewed_at?"Effective":"Unreviewed"):"Superseded"}</b></summary><dl className="historyFacts"><div><dt>Reviewed</dt><dd>{formatDate(String(p.reviewed_at??""))}</dd></div><div><dt>Authority</dt><dd>{p.review_authority??"Unreviewed"}</dd></div><div><dt>Effective</dt><dd>{formatDate(String(p.effective_at??""))}</dd></div><div><dt>Supersedes</dt><dd>{p.supersedes_policy_id??"Initial policy"}</dd></div><div><dt>Basis</dt><dd>{p.documented_basis??"No reviewed basis recorded"}</dd></div><div><dt>License</dt><dd>{[p.license_type,p.license_version].filter(Boolean).join(" ")||"Not recorded"}</dd></div></dl><h4>Permitted-use grants</h4><ul className="historyGrants">{Object.entries(p.grants??{}).map(([use,state])=><li key={use}>{humanize(use)}: {show(state)}</li>)}</ul>{p.policy_notes&&<p><b>Policy notes:</b> {String(p.policy_notes)}</p>}</details>)}</section>}
