"use client";
import Link from "next/link";
import {useEffect, useState} from "react";
import {api, siteScope} from "@/lib/api";
import {formatDate, formatNumber, humanize} from "@/lib/format";
import {EmptyState, ErrorState, LoadingState, MetricCard, PageHeader, StatusBadge} from "./ui";
type Pipeline={key:string;name:string;purpose:string;classification:string;health:string;health_reason:string;schedule_status:string;cadence:string|null;latest_success:string|null;run_count:number;href:string}; type Pipelines={items:Pipeline[];total:number;health_counts:Record<string,number>};
type ReliabilityItem={schedule:string;source_health:{state:string;latest_ingestion_success:string|null;latest_provider_reporting_date:string|null;provider_lag_days:number|null};automation_health:{state:string;next_due_at:string|null;last_obligation_status:string|null;last_completion_outcome:string|null;timeliness:string;pending_obligations:number;overdue_obligations:number;orchestration_run_count:number;retry_profile:string}};
type Reliability={items:ReliabilityItem[];executor_liveness:{SCHEDULER:boolean;WORKER:boolean}};
export function SystemOverview(){const[data,setData]=useState<Pipelines>();const[reliability,setReliability]=useState<Reliability>();const[error,setError]=useState<string>();useEffect(()=>{Promise.all([api<Pipelines>(`/api/v1/system/pipelines?${siteScope()}`),api<Reliability>(`/api/v1/capabilities?${siteScope()}`)]).then(([pipelines,health])=>{setData(pipelines);setReliability(health)}).catch((value:Error)=>setError(value.message));},[]);const attention=data?(["FAILING","STALE","MISSED_UNSATISFIED","EXECUTOR_OFFLINE","PROVIDER_DATA_PENDING"] as const).reduce((total,state)=>total+(data.health_counts[state]??0),0):0;return <><PageHeader eyebrow="Operational intelligence" title="System" description="Can GIS currently produce trustworthy intelligence, and what is affected when a source or pipeline is unavailable?"/><SystemNav/>{error?<ErrorState message={error}/>:!data||!reliability?<LoadingState/>:<><div className="notice"><strong>Execution services</strong><p>Scheduler: {reliability.executor_liveness.SCHEDULER?"Running":"Offline"}. Worker: {reliability.executor_liveness.WORKER?"Running":"Offline"}. Source health describes available data; automation health describes whether GIS can satisfy upcoming data obligations.</p></div><div className="metrics"><MetricCard label="Registered pipelines" value={data.total} detail="Collectors and local processing"/><MetricCard label="Healthy" value={data.health_counts.HEALTHY??0} detail="Current and successful"/><MetricCard label="Needs attention" value={attention} detail="Excludes disabled and not-yet-due pipelines"/></div><ReliabilityTable items={reliability.items}/></>}</>}
function ReliabilityTable({items}:{items:ReliabilityItem[]}){return <div className="tableWrap"><table><thead><tr><th>Pipeline</th><th>Source health</th><th>Automation health</th><th>Latest source data</th><th>Next obligation</th><th>Completion</th></tr></thead><tbody>{items.map((item)=><tr key={item.schedule}><td><strong>{item.schedule}</strong><small>{humanize(item.automation_health.retry_profile)}</small></td><td><StatusBadge>{humanize(item.source_health.state)}</StatusBadge>{item.source_health.latest_provider_reporting_date?<small>Provider period: {item.source_health.latest_provider_reporting_date}{item.source_health.provider_lag_days===null?"":` · ${item.source_health.provider_lag_days}d lag`}</small>:null}</td><td><StatusBadge>{humanize(item.automation_health.state)}</StatusBadge><small>{item.automation_health.pending_obligations} pending · {item.automation_health.overdue_obligations} overdue · {item.automation_health.orchestration_run_count} orchestration runs</small></td><td>{formatDate(item.source_health.latest_ingestion_success)}</td><td>{formatDate(item.automation_health.next_due_at)}</td><td>{humanize(item.automation_health.timeliness)}<small>{humanize(item.automation_health.last_completion_outcome??item.automation_health.last_obligation_status??"not yet due")}</small></td></tr>)}</tbody></table></div>}
export function SystemNav(){return <nav className="subnav" aria-label="System"><Link href="/system">Overview</Link><Link href="/system/pipelines">Pipelines</Link><Link href="/system/sources">Data sources</Link><Link href="/system/data-flow">Data flow</Link><Link href="/system/runs">Run history</Link></nav>}
export function PipelineTable({items}:{items:Pipeline[]}){return items.length===0?<EmptyState title="No pipelines registered" detail="Capabilities may exist without an operational pipeline registration."/>:<div className="tableWrap"><table><thead><tr><th>Pipeline</th><th>Health</th><th>Classification</th><th>Schedule</th><th>Latest success</th></tr></thead><tbody>{items.map((item)=><tr key={item.key}><td><Link href={item.href}>{item.name}</Link><small>{item.purpose}</small></td><td><StatusBadge>{humanize(item.health)}</StatusBadge><small>{item.health_reason}</small></td><td>{humanize(item.classification)}</td><td>{item.cadence??humanize(item.schedule_status)}</td><td>{formatDate(item.latest_success)}</td></tr>)}</tbody></table></div>}
export function PipelineList(){const[data,setData]=useState<Pipelines>();const[error,setError]=useState<string>();useEffect(()=>{api<Pipelines>(`/api/v1/system/pipelines?${siteScope()}`).then(setData).catch((value:Error)=>setError(value.message));},[]);return <><PageHeader eyebrow="System" title="Pipelines" description="Collection and processing workflows, their purpose, cadence, health, reliability, cost, and downstream impact."/><SystemNav/>{error?<ErrorState message={error}/>:!data?<LoadingState/>:<PipelineTable items={data.items}/>}</>}
type Source={key:string;name:string;provider:string;type:string;acquisition_method:string;connection_status:string;rights_status:string;last_success:string|null;stored_source_records:number;cost:string;powering:string[];href:string};
export function SourceList(){const[data,setData]=useState<{items:Source[];total:number}>();const[error,setError]=useState<string>();useEffect(()=>{api<{items:Source[];total:number}>(`/api/v1/system/sources?${siteScope()}`).then(setData).catch((value:Error)=>setError(value.message));},[]);return <><PageHeader eyebrow="System" title="Data sources" description="Where GIS information originates, how it is acquired, its governed connection state, and which capabilities it powers."/><SystemNav/>{error?<ErrorState message={error}/>:!data?<LoadingState/>:<div className="tableWrap"><table><thead><tr><th>Source</th><th>Provider / type</th><th>Connection</th><th>Rights</th><th>Stored source records</th><th>Last success</th><th>Powering</th></tr></thead><tbody>{data.items.map((item)=><tr key={item.key}><td><Link href={item.href}>{item.name}</Link><small>{humanize(item.acquisition_method)} · {item.cost}</small></td><td>{item.provider}<small>{humanize(item.type)}</small></td><td><StatusBadge>{humanize(item.connection_status)}</StatusBadge></td><td>{humanize(item.rights_status)}</td><td>{formatNumber(item.stored_source_records)}</td><td>{formatDate(item.last_success)}</td><td>{item.powering.length?item.powering.map(humanize).join(", "):"No registered pipeline dependency"}</td></tr>)}</tbody></table></div>}</>}
type Flow={sources:Source[];pipelines:Pipeline[];pipeline_edges:{from:string;to:string;policy:string}[];assets:{id:string;canonical_name:string;layer:string}[];methodology:string};
export function DataFlow(){const[data,setData]=useState<Flow>();const[error,setError]=useState<string>();useEffect(()=>{api<Flow>(`/api/v1/system/data-flow?${siteScope()}`).then(setData).catch((value:Error)=>setError(value.message));},[]);return <><PageHeader eyebrow="System" title="How GIS is powered" description="Real registered sources, pipelines, governed data assets, analysis, and decision-intelligence dependencies."/><SystemNav/>{error?<ErrorState message={error}/>:!data?<LoadingState/>:<><p className="notice">{data.methodology}</p><div className="flowLayers"><section className="flowLayer"><h2>Sources</h2><div className="flowNodes">{data.sources.map((item)=><Link key={item.key} href={item.href}>{item.name}{item.powering.length?` → ${item.powering.map(humanize).join(", ")}`:" · dependency not mapped"}</Link>)}</div></section><div aria-hidden="true">↓</div><section className="flowLayer"><h2>Collection and processing</h2><div className="flowNodes">{data.pipelines.map((item)=><Link key={item.key} href={item.href}>{item.name} · {humanize(item.health)}</Link>)}</div>{data.pipeline_edges.length?<ul>{data.pipeline_edges.map((edge)=><li key={`${edge.from}-${edge.to}`}>{humanize(edge.from)} → {humanize(edge.to)} ({humanize(edge.policy)})</li>)}</ul>:<p>No pipeline-to-pipeline dependency edges are registered.</p>}</section><div aria-hidden="true">↓</div><section className="flowLayer"><h2>Governed data assets and intelligence</h2><div className="flowNodes">{data.assets.map((item)=><span key={item.id}>{item.canonical_name} · {humanize(item.layer)}</span>)}</div></section></div></>}</>}
