"use client";
import Link from "next/link";
import {useEffect, useState} from "react";
import {api, siteScope} from "@/lib/api";
import {formatDate, humanize} from "@/lib/format";
import {EmptyState, ErrorState, LoadingState, MetricCard, PageHeader, StatusBadge} from "./ui";
type Pipeline={key:string;name:string;purpose:string;classification:string;health:string;health_reason:string;schedule_status:string;cadence:string|null;latest_success:string|null;run_count:number;href:string}; type Pipelines={items:Pipeline[];total:number;health_counts:Record<string,number>};
export function SystemOverview(){const[data,setData]=useState<Pipelines>();const[error,setError]=useState<string>();useEffect(()=>{api<Pipelines>(`/api/v1/system/pipelines?${siteScope()}`).then(setData).catch((value:Error)=>setError(value.message));},[]);return <><PageHeader eyebrow="Operational intelligence" title="System" description="Can GIS currently produce trustworthy intelligence, and what is affected when a source or pipeline is unavailable?"/><SystemNav/>{error?<ErrorState message={error}/>:!data?<LoadingState/>:<><div className="metrics"><MetricCard label="Registered pipelines" value={data.total} detail="Collectors and local processing"/><MetricCard label="Healthy" value={data.health_counts.HEALTHY??0} detail="Current and successful"/><MetricCard label="Needs attention" value={(data.health_counts.FAILING??0)+(data.health_counts.STALE??0)+(data.health_counts.INSUFFICIENT_HISTORY??0)} detail="Transparent health states"/></div><PipelineTable items={data.items}/></>}</>}
export function SystemNav(){return <nav className="subnav" aria-label="System"><Link href="/system">Overview</Link><Link href="/system/pipelines">Pipelines</Link><Link href="/system/sources">Data sources</Link><Link href="/system/data-flow">Data flow</Link><Link href="/system/runs">Run history</Link></nav>}
export function PipelineTable({items}:{items:Pipeline[]}){return items.length===0?<EmptyState title="No pipelines registered" detail="Capabilities may exist without an operational pipeline registration."/>:<div className="tableWrap"><table><thead><tr><th>Pipeline</th><th>Health</th><th>Classification</th><th>Schedule</th><th>Latest success</th></tr></thead><tbody>{items.map((item)=><tr key={item.key}><td><Link href={item.href}>{item.name}</Link><small>{item.purpose}</small></td><td><StatusBadge>{humanize(item.health)}</StatusBadge><small>{item.health_reason}</small></td><td>{humanize(item.classification)}</td><td>{item.cadence??humanize(item.schedule_status)}</td><td>{formatDate(item.latest_success)}</td></tr>)}</tbody></table></div>}
export function PipelineList(){const[data,setData]=useState<Pipelines>();const[error,setError]=useState<string>();useEffect(()=>{api<Pipelines>(`/api/v1/system/pipelines?${siteScope()}`).then(setData).catch((value:Error)=>setError(value.message));},[]);return <><PageHeader eyebrow="System" title="Pipelines" description="Collection and processing workflows, their purpose, cadence, health, reliability, cost, and downstream impact."/><SystemNav/>{error?<ErrorState message={error}/>:!data?<LoadingState/>:<PipelineTable items={data.items}/>}</>}
type Source={key:string;name:string;provider:string;type:string;acquisition_method:string;connection_status:string;rights_status:string;last_success:string|null;records:number;cost:string;powering:string[];href:string};
export function SourceList(){const[data,setData]=useState<{items:Source[];total:number}>();const[error,setError]=useState<string>();useEffect(()=>{api<{items:Source[];total:number}>(`/api/v1/system/sources?${siteScope()}`).then(setData).catch((value:Error)=>setError(value.message));},[]);return <><PageHeader eyebrow="System" title="Data sources" description="Where GIS information originates, how it is acquired, its governed connection state, and which capabilities it powers."/><SystemNav/>{error?<ErrorState message={error}/>:!data?<LoadingState/>:<div className="tableWrap"><table><thead><tr><th>Source</th><th>Provider / type</th><th>Connection</th><th>Rights</th><th>Last success</th><th>Powering</th></tr></thead><tbody>{data.items.map((item)=><tr key={item.key}><td><Link href={item.href}>{item.name}</Link><small>{humanize(item.acquisition_method)} · {item.cost}</small></td><td>{item.provider}<small>{humanize(item.type)}</small></td><td><StatusBadge>{humanize(item.connection_status)}</StatusBadge></td><td>{humanize(item.rights_status)}</td><td>{formatDate(item.last_success)}</td><td>{item.powering.length?item.powering.map(humanize).join(", "):"No registered pipeline dependency"}</td></tr>)}</tbody></table></div>}</>}
type Flow={sources:Source[];pipelines:Pipeline[];pipeline_edges:{from:string;to:string;policy:string}[];assets:{id:string;canonical_name:string;layer:string}[];methodology:string};
export function DataFlow(){const[data,setData]=useState<Flow>();const[error,setError]=useState<string>();useEffect(()=>{api<Flow>(`/api/v1/system/data-flow?${siteScope()}`).then(setData).catch((value:Error)=>setError(value.message));},[]);return <><PageHeader eyebrow="System" title="How GIS is powered" description="Real registered sources, pipelines, governed data assets, analysis, and decision-intelligence dependencies."/><SystemNav/>{error?<ErrorState message={error}/>:!data?<LoadingState/>:<><p className="notice">{data.methodology}</p><div className="flowLayers"><section className="flowLayer"><h2>Sources</h2><div className="flowNodes">{data.sources.map((item)=><Link key={item.key} href={item.href}>{item.name}{item.powering.length?` → ${item.powering.map(humanize).join(", ")}`:" · dependency not mapped"}</Link>)}</div></section><div aria-hidden="true">↓</div><section className="flowLayer"><h2>Collection and processing</h2><div className="flowNodes">{data.pipelines.map((item)=><Link key={item.key} href={item.href}>{item.name} · {humanize(item.health)}</Link>)}</div>{data.pipeline_edges.length?<ul>{data.pipeline_edges.map((edge)=><li key={`${edge.from}-${edge.to}`}>{humanize(edge.from)} → {humanize(edge.to)} ({humanize(edge.policy)})</li>)}</ul>:<p>No pipeline-to-pipeline dependency edges are registered.</p>}</section><div aria-hidden="true">↓</div><section className="flowLayer"><h2>Governed data assets and intelligence</h2><div className="flowNodes">{data.assets.map((item)=><span key={item.id}>{item.canonical_name} · {humanize(item.layer)}</span>)}</div></section></div></>}</>}
