"use client";

import {useEffect, useState} from "react";
import {api, siteScope} from "@/lib/api";
import {EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge} from "./ui";

type CapabilityItem = {
  schedule: string; status: string; latest_success: string | null; stale_since: string | null; reason: string | null;
  source_health: {state: string; latest_ingestion_success: string | null; latest_provider_reporting_date: string | null; provider_lag_days: number | null; freshness_sla_seconds: number | null; stale_since: string | null};
  automation_health: {state: string; next_due_at: string | null; last_obligation_status: string | null; last_obligation_due_at: string | null; last_completion_outcome: string | null; timeliness: string; pending_obligations: number; overdue_obligations: number; orchestration_run_count: number; scheduler_alive: boolean; worker_alive: boolean; retry_profile: string};
};
type Capability = {items: CapabilityItem[]; executor_liveness: {SCHEDULER: boolean; WORKER: boolean}; experience: {lab_observations: number; field_observations: number; crux_state: string; semantics: string}; fixture_ai_provider: boolean; production_ai_operational: boolean};
export function SystemPage() {
  const [data, setData] = useState<Capability>(); const [error, setError] = useState<string>();
  useEffect(() => { api<Capability>(`/api/v1/capabilities?${siteScope()}`).then(setData).catch((value: Error) => setError(value.message)); }, []);
  return <><PageHeader eyebrow="Operations" title="System & capabilities" description="Whether GIS has current source data and whether automation can satisfy the next obligation."/>{error ? <ErrorState message={error}/> : !data ? <LoadingState/> : <><div className="notice"><strong>Execution services</strong><p>Scheduler: {data.executor_liveness.SCHEDULER ? "Running" : "Offline"}. Worker: {data.executor_liveness.WORKER ? "Running" : "Offline"}. An enabled schedule is not assurance of execution when either service is offline.</p></div><div className="notice"><strong>Page experience evidence</strong><p>{data.experience.lab_observations} Lighthouse LAB observations stored. CrUX FIELD: {data.experience.crux_state}. {data.experience.semantics}</p></div><div className="notice"><strong>AI provider</strong><p>{data.fixture_ai_provider ? "Fixture / development recommendation provider" : "Not configured"}. Production AI operational: {data.production_ai_operational ? "Yes" : "No"}.</p></div>{data.items.length === 0 ? <EmptyState title="No schedules are configured." detail="Capabilities may be implemented without an operational collection schedule."/> : <div className="tableWrap"><table><thead><tr><th>Pipeline</th><th>Source health</th><th>Automation health</th><th>Latest ingestion</th><th>Next obligation</th><th>Obligations</th><th>Operational note</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.schedule}><td><strong>{item.schedule}</strong><br/><small>{item.automation_health.retry_profile}</small></td><td><StatusBadge>{item.source_health.state}</StatusBadge></td><td><StatusBadge>{item.automation_health.state}</StatusBadge><br/><small>{item.automation_health.orchestration_run_count} orchestration runs</small></td><td>{item.source_health.latest_ingestion_success ?? "No source history"}</td><td>{item.automation_health.next_due_at ?? "Not scheduled"}<br/><small>Last: {item.automation_health.last_completion_outcome ?? item.automation_health.last_obligation_status ?? "Not yet due"}</small></td><td>{item.automation_health.pending_obligations} pending / {item.automation_health.overdue_obligations} overdue</td><td>{item.reason ?? "—"}</td></tr>)}</tbody></table></div>}</>}</>;
}
